import type { WeekTopicSeed } from '../types';

/**
 * Lộ trình Lớp 2 — Toán và Tiếng Việt, tuần 1-6 (bộ Kết nối tri thức).
 *
 * 5 câu mỗi tuần. Trọng tâm Lớp 2 học kỳ I là **cộng, trừ có nhớ trong phạm vi
 * 20** và **từ chỉ hoạt động / đặc điểm**, nên phần lớn câu hỏi ở đây bám hai
 * mảng đó thay vì dàn đều mọi chủ đề.
 *
 * Ghi chú về đáp án: trong tệp dữ liệu, đáp án đúng luôn đặt ở vị trí đầu
 * (`correctAnswer: 0`). `shuffleQuestionOptions` trộn lại thứ tự A/B/C/D mỗi lần
 * tạo đề, nên vị trí trong tệp không mang thông tin gì — xem `lib/quizEngine.ts`.
 */

const MATH_UNIT_1 = 'Ôn tập & Phép cộng có nhớ trong phạm vi 20';
const MATH_UNIT_2 = 'Phép trừ có nhớ & Giải toán có lời văn';

export const GRADE2_MATH_WEEKS: WeekTopicSeed[] = [
  {
    subject: 'Toán',
    weekNumber: 1,
    unit: MATH_UNIT_1,
    title: 'Ôn tập các số đến 100',
    difficulty: 1,
    questions: [
      {
        id: 'g2-toan-w01-q1',
        subject: 'Toán',
        content: 'Số 57 gồm mấy chục và mấy đơn vị?',
        options: ['5 chục và 7 đơn vị', '7 chục và 5 đơn vị', '57 chục', '5 chục và 70 đơn vị'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Chữ số bên trái là hàng chục (5), bên phải là hàng đơn vị (7).',
      },
      {
        id: 'g2-toan-w01-q2',
        subject: 'Toán',
        content: 'Số lớn nhất có hai chữ số là số nào?',
        options: ['99', '100', '90', '98'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '100 đã có ba chữ số, nên số hai chữ số lớn nhất là 99.',
      },
      {
        id: 'g2-toan-w01-q3',
        subject: 'Toán',
        content: 'Số bé nhất có hai chữ số là số nào?',
        options: ['10', '11', '01', '20'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Số hai chữ số nhỏ nhất là 10; "01" không phải cách viết số hợp lệ.',
      },
      {
        id: 'g2-toan-w01-q4',
        subject: 'Toán',
        content: 'Sắp xếp 45, 54, 44 theo thứ tự từ bé đến lớn.',
        options: ['44, 45, 54', '44, 54, 45', '45, 44, 54', '54, 45, 44'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'So hàng chục trước: 44 và 45 cùng 4 chục, xét đơn vị 4 < 5; còn 54 có 5 chục nên lớn nhất.',
      },
      {
        id: 'g2-toan-w01-q5',
        subject: 'Toán',
        content: 'Số 80 đọc như thế nào?',
        options: ['Tám mươi', 'Tám không', 'Tám chục không', 'Tám trăm'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Hàng đơn vị là 0 nên chỉ đọc phần chục: tám mươi.',
      },
    ],
  },
  {
    subject: 'Toán',
    weekNumber: 2,
    unit: MATH_UNIT_1,
    title: 'Tia số, số liền trước - liền sau',
    difficulty: 1,
    questions: [
      {
        id: 'g2-toan-w02-q1',
        subject: 'Toán',
        content: 'Số liền sau của 39 là số nào?',
        options: ['40', '38', '49', '30'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Thêm 1 vào 39 được 40.',
      },
      {
        id: 'g2-toan-w02-q2',
        subject: 'Toán',
        content: 'Số liền trước của 70 là số nào?',
        options: ['69', '71', '60', '79'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Bớt 1 khỏi 70 được 69.',
      },
      {
        id: 'g2-toan-w02-q3',
        subject: 'Toán',
        content: 'Trên tia số, số nào nằm giữa 25 và 27?',
        options: ['26', '24', '28', '30'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Đếm 25, 26, 27 — số ở giữa là 26.',
      },
      {
        id: 'g2-toan-w02-q4',
        subject: 'Toán',
        content: 'Đếm thêm 5: 10, 15, 20, ...?',
        options: ['25', '21', '30', '24'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Mỗi bước cộng thêm 5: 20 + 5 = 25.',
      },
      {
        id: 'g2-toan-w02-q5',
        subject: 'Toán',
        content: 'Số liền trước và số liền sau của 50 lần lượt là?',
        options: ['49 và 51', '51 và 49', '40 và 60', '48 và 52'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Liền trước là bớt 1 (49), liền sau là thêm 1 (51).',
      },
    ],
  },
  {
    subject: 'Toán',
    weekNumber: 3,
    unit: MATH_UNIT_1,
    title: 'Phép cộng có nhớ trong phạm vi 20',
    difficulty: 1,
    questions: [
      {
        id: 'g2-toan-w03-q1',
        subject: 'Toán',
        content: '9 + 5 = ?',
        options: ['14', '13', '15', '12'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Tách 5 thành 1 và 4: 9 + 1 = 10, rồi 10 + 4 = 14.',
      },
      {
        id: 'g2-toan-w03-q2',
        subject: 'Toán',
        content: '8 + 7 = ?',
        options: ['15', '14', '16', '13'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Tách 7 thành 2 và 5: 8 + 2 = 10, rồi 10 + 5 = 15.',
      },
      {
        id: 'g2-toan-w03-q3',
        subject: 'Toán',
        content: '9 + 9 = ?',
        options: ['18', '17', '19', '16'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '9 + 1 = 10, còn lại 8: 10 + 8 = 18.',
      },
      {
        id: 'g2-toan-w03-q4',
        subject: 'Toán',
        content: '7 + 6 = ?',
        options: ['13', '12', '14', '11'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Tách 6 thành 3 và 3: 7 + 3 = 10, rồi 10 + 3 = 13.',
      },
      {
        id: 'g2-toan-w03-q5',
        subject: 'Toán',
        content: 'Để tính 9 + 6, ta làm 9 + 1 = 10 rồi cộng thêm mấy?',
        options: ['5', '6', '4', '1'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Đã lấy 1 từ số 6, còn lại 5 nên 10 + 5 = 15.',
      },
    ],
  },
  {
    subject: 'Toán',
    weekNumber: 4,
    unit: MATH_UNIT_1,
    title: '8, 7, 6 cộng với một số',
    difficulty: 1,
    questions: [
      {
        id: 'g2-toan-w04-q1',
        subject: 'Toán',
        content: '8 + 4 = ?',
        options: ['12', '11', '13', '14'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '8 + 2 = 10, còn lại 2: 10 + 2 = 12.',
      },
      {
        id: 'g2-toan-w04-q2',
        subject: 'Toán',
        content: '7 + 8 = ?',
        options: ['15', '14', '16', '13'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '7 + 3 = 10, còn lại 5: 10 + 5 = 15.',
      },
      {
        id: 'g2-toan-w04-q3',
        subject: 'Toán',
        content: '6 + 9 = ?',
        options: ['15', '14', '16', '17'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Đổi chỗ cho dễ: 9 + 6 = 15.',
      },
      {
        id: 'g2-toan-w04-q4',
        subject: 'Toán',
        content: '8 + 8 = ?',
        options: ['16', '15', '17', '18'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '8 + 2 = 10, còn lại 6: 10 + 6 = 16.',
      },
      {
        id: 'g2-toan-w04-q5',
        subject: 'Toán',
        content: '6 + 5 = ?',
        options: ['11', '10', '12', '13'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '6 + 4 = 10, còn lại 1: 10 + 1 = 11.',
      },
    ],
  },
  {
    subject: 'Toán',
    weekNumber: 5,
    unit: MATH_UNIT_2,
    title: 'Phép trừ có nhớ trong phạm vi 20',
    difficulty: 1,
    questions: [
      {
        id: 'g2-toan-w05-q1',
        subject: 'Toán',
        content: '13 - 5 = ?',
        options: ['8', '7', '9', '6'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '13 - 3 = 10, rồi 10 - 2 = 8.',
      },
      {
        id: 'g2-toan-w05-q2',
        subject: 'Toán',
        content: '12 - 9 = ?',
        options: ['3', '2', '4', '5'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '12 - 2 = 10, rồi 10 - 7 = 3.',
      },
      {
        id: 'g2-toan-w05-q3',
        subject: 'Toán',
        content: '15 - 6 = ?',
        options: ['9', '8', '10', '7'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '15 - 5 = 10, rồi 10 - 1 = 9.',
      },
      {
        id: 'g2-toan-w05-q4',
        subject: 'Toán',
        content: '11 - 4 = ?',
        options: ['7', '6', '8', '5'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '11 - 1 = 10, rồi 10 - 3 = 7.',
      },
      {
        id: 'g2-toan-w05-q5',
        subject: 'Toán',
        content: '14 - 8 = ?',
        options: ['6', '5', '7', '8'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '14 - 4 = 10, rồi 10 - 4 = 6.',
      },
    ],
  },
  {
    subject: 'Toán',
    weekNumber: 6,
    unit: MATH_UNIT_2,
    title: 'Giải bài toán có lời văn',
    difficulty: 1,
    questions: [
      {
        id: 'g2-toan-w06-q1',
        subject: 'Toán',
        content: 'Lan có 12 cái kẹo, cho bạn 5 cái. Lan còn lại mấy cái kẹo?',
        options: ['7 cái', '8 cái', '17 cái', '6 cái'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '"Cho bạn" là bớt đi nên làm phép trừ: 12 - 5 = 7.',
      },
      {
        id: 'g2-toan-w06-q2',
        subject: 'Toán',
        content: 'Trong vườn có 8 cây cam và 7 cây bưởi. Hỏi có tất cả mấy cây?',
        options: ['15 cây', '14 cây', '16 cây', '1 cây'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '"Tất cả" là gộp lại nên làm phép cộng: 8 + 7 = 15.',
      },
      {
        id: 'g2-toan-w06-q3',
        subject: 'Toán',
        content: 'Hộp thứ nhất có 9 viên bi. Hộp thứ hai có nhiều hơn hộp thứ nhất 3 viên. Hộp thứ hai có mấy viên?',
        options: ['12 viên', '6 viên', '9 viên', '13 viên'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '"Nhiều hơn" thì cộng thêm: 9 + 3 = 12.',
      },
      {
        id: 'g2-toan-w06-q4',
        subject: 'Toán',
        content: 'An cao 105 cm. Bình thấp hơn An 8 cm. Bình cao bao nhiêu xăng-ti-mét?',
        options: ['97 cm', '113 cm', '103 cm', '87 cm'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '"Thấp hơn" thì bớt đi: 105 - 8 = 97 cm.',
      },
      {
        id: 'g2-toan-w06-q5',
        subject: 'Toán',
        content: 'Lớp có 20 học sinh, trong đó 12 bạn là nữ. Hỏi lớp có mấy bạn nam?',
        options: ['8 bạn', '9 bạn', '32 bạn', '7 bạn'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Lấy tổng trừ đi số bạn nữ: 20 - 12 = 8.',
      },
    ],
  },
];

const VIET_UNIT_1 = 'Em là học sinh & Từ chỉ hoạt động, đặc điểm';
const VIET_UNIT_2 = 'Câu giới thiệu & Tình cảm gia đình';

export const GRADE2_VIETNAMESE_WEEKS: WeekTopicSeed[] = [
  {
    subject: 'Tiếng Việt',
    weekNumber: 1,
    unit: VIET_UNIT_1,
    title: 'Em là học sinh',
    difficulty: 1,
    questions: [
      {
        id: 'g2-tv-w01-q1',
        subject: 'Tiếng Việt',
        content: 'Từ nào chỉ sự vật ở trường học?',
        options: ['bảng đen', 'chạy', 'đẹp', 'nhanh'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện từ và câu',
        explanation: '"bảng đen" là một đồ vật; ba từ còn lại chỉ hoạt động hoặc đặc điểm.',
      },
      {
        id: 'g2-tv-w01-q2',
        subject: 'Tiếng Việt',
        content: 'Câu nào là câu giới thiệu về bản thân?',
        options: [
          'Em là học sinh lớp 2.',
          'Em đang quét sân.',
          'Bông hoa rất đẹp.',
          'Trời hôm nay mưa.',
        ],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện từ và câu',
        explanation: 'Câu giới thiệu cho biết ai đó "là" gì.',
      },
      {
        id: 'g2-tv-w01-q3',
        subject: 'Tiếng Việt',
        content: 'Từ nào chỉ người làm việc ở trường học?',
        options: ['cô giáo', 'cái ghế', 'quyển vở', 'sân trường'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện từ và câu',
        explanation: 'Chỉ "cô giáo" là người, còn lại là đồ vật và nơi chốn.',
      },
      {
        id: 'g2-tv-w01-q4',
        subject: 'Tiếng Việt',
        content: 'Bạn Nam học lớp mấy?',
        passage: 'Nam là học sinh lớp 2A. Nam rất thích giờ Tiếng Việt vì được đọc truyện.',
        options: ['Lớp 2A', 'Lớp 1A', 'Lớp 3A', 'Lớp 2B'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Tập đọc',
        explanation: 'Câu đầu nói rõ: "Nam là học sinh lớp 2A."',
      },
      {
        id: 'g2-tv-w01-q5',
        subject: 'Tiếng Việt',
        content: 'Tên riêng của người phải viết như thế nào?',
        options: [
          'Viết hoa chữ đầu mỗi tiếng',
          'Viết thường tất cả',
          'Viết hoa toàn bộ',
          'Viết hoa tiếng cuối',
        ],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Chính tả',
        explanation: 'Ví dụ: Nguyễn Minh Khang — mỗi tiếng viết hoa chữ đầu.',
      },
    ],
  },
  {
    subject: 'Tiếng Việt',
    weekNumber: 2,
    unit: VIET_UNIT_1,
    title: 'Từ chỉ hoạt động, từ chỉ thời gian',
    difficulty: 1,
    questions: [
      {
        id: 'g2-tv-w02-q1',
        subject: 'Tiếng Việt',
        content: 'Từ nào chỉ hoạt động?',
        options: ['đọc', 'sách', 'đẹp', 'xanh'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện từ và câu',
        explanation: '"đọc" là việc con làm được; "sách" là đồ vật, "đẹp" và "xanh" là đặc điểm.',
      },
      {
        id: 'g2-tv-w02-q2',
        subject: 'Tiếng Việt',
        content: 'Từ nào chỉ thời gian?',
        options: ['buổi sáng', 'quyển vở', 'chạy', 'cao'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện từ và câu',
        explanation: '"buổi sáng" cho biết lúc nào, đó là từ chỉ thời gian.',
      },
      {
        id: 'g2-tv-w02-q3',
        subject: 'Tiếng Việt',
        content: 'Trong câu "Em quét nhà.", từ chỉ hoạt động là từ nào?',
        options: ['quét', 'em', 'nhà', 'quét nhà'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện từ và câu',
        explanation: '"quét" là việc em làm; "nhà" là sự vật bị quét.',
      },
      {
        id: 'g2-tv-w02-q4',
        subject: 'Tiếng Việt',
        content: 'Từ nào KHÔNG chỉ hoạt động?',
        options: ['bàn ghế', 'viết', 'hát', 'nhảy'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện từ và câu',
        explanation: '"bàn ghế" là đồ vật, không phải việc làm.',
      },
      {
        id: 'g2-tv-w02-q5',
        subject: 'Tiếng Việt',
        content: 'Chọn từ điền vào chỗ trống: "Buổi ... em đi học."',
        options: ['sáng', 'chạy', 'đẹp', 'cặp'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện từ và câu',
        explanation: 'Sau "buổi" cần một từ chỉ thời gian: buổi sáng.',
      },
    ],
  },
  {
    subject: 'Tiếng Việt',
    weekNumber: 3,
    unit: VIET_UNIT_1,
    title: 'Từ chỉ đặc điểm và dấu câu',
    difficulty: 1,
    questions: [
      {
        id: 'g2-tv-w03-q1',
        subject: 'Tiếng Việt',
        content: 'Từ nào chỉ đặc điểm?',
        options: ['cao', 'chạy', 'cặp sách', 'mẹ'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện từ và câu',
        explanation: '"cao" cho biết hình dáng, đó là từ chỉ đặc điểm.',
      },
      {
        id: 'g2-tv-w03-q2',
        subject: 'Tiếng Việt',
        content: 'Câu hỏi kết thúc bằng dấu gì?',
        options: ['Dấu chấm hỏi', 'Dấu chấm', 'Dấu phẩy', 'Dấu chấm than'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện từ và câu',
        explanation: 'Câu dùng để hỏi thì cuối câu đặt dấu chấm hỏi (?).',
      },
      {
        id: 'g2-tv-w03-q3',
        subject: 'Tiếng Việt',
        content: 'Điền dấu câu thích hợp: "Bạn tên là gì___"',
        options: ['?', '.', ',', '!'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện từ và câu',
        explanation: 'Đây là câu hỏi nên dùng dấu chấm hỏi.',
      },
      {
        id: 'g2-tv-w03-q4',
        subject: 'Tiếng Việt',
        content: 'Trong câu "Bông hoa rất thơm.", từ chỉ đặc điểm là từ nào?',
        options: ['thơm', 'bông hoa', 'rất', 'hoa'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện từ và câu',
        explanation: '"thơm" cho biết mùi của bông hoa, đó là đặc điểm.',
      },
      {
        id: 'g2-tv-w03-q5',
        subject: 'Tiếng Việt',
        content: 'Dấu phẩy trong câu dùng để làm gì?',
        options: [
          'Tách các từ cùng loại trong câu',
          'Kết thúc câu',
          'Thay cho dấu hỏi',
          'Viết hoa chữ đầu',
        ],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện từ và câu',
        explanation: 'Ví dụ: "Em có bút, thước và vở." — dấu phẩy tách các đồ vật.',
      },
    ],
  },
  {
    subject: 'Tiếng Việt',
    weekNumber: 4,
    unit: VIET_UNIT_2,
    title: 'Câu giới thiệu',
    difficulty: 1,
    questions: [
      {
        id: 'g2-tv-w04-q1',
        subject: 'Tiếng Việt',
        content: 'Câu nào là câu giới thiệu?',
        options: [
          'Bố em là bác sĩ.',
          'Bố em đang đọc báo.',
          'Bố em rất cao.',
          'Bố em ơi!',
        ],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện từ và câu',
        explanation: 'Câu giới thiệu cho biết ai đó "là" gì; câu còn lại nêu hoạt động hoặc đặc điểm.',
      },
      {
        id: 'g2-tv-w04-q2',
        subject: 'Tiếng Việt',
        content: 'Câu giới thiệu thường có từ nào ở giữa?',
        options: ['là', 'rất', 'đang', 'không'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện từ và câu',
        explanation: 'Mẫu câu quen thuộc: "... là ...".',
      },
      {
        id: 'g2-tv-w04-q3',
        subject: 'Tiếng Việt',
        content: 'Chọn câu giới thiệu đúng về con vật.',
        options: [
          'Con mèo là vật nuôi trong nhà.',
          'Con mèo đang ngủ.',
          'Con mèo rất đáng yêu.',
          'Con mèo kêu meo meo.',
        ],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện từ và câu',
        explanation: 'Chỉ câu đầu dùng mẫu "... là ..." để giới thiệu.',
      },
      {
        id: 'g2-tv-w04-q4',
        subject: 'Tiếng Việt',
        content: 'Trong câu "Hà Nội là thủ đô của nước ta.", bộ phận giới thiệu là phần nào?',
        options: [
          'là thủ đô của nước ta',
          'Hà Nội',
          'của nước ta',
          'thủ đô',
        ],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện từ và câu',
        explanation: 'Phần sau từ "là" cho biết Hà Nội là gì.',
      },
      {
        id: 'g2-tv-w04-q5',
        subject: 'Tiếng Việt',
        content: 'Câu "Em rất thích đọc sách." thuộc loại câu nào?',
        options: [
          'Câu nêu hoạt động, sở thích',
          'Câu giới thiệu',
          'Câu hỏi',
          'Câu cảm',
        ],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện từ và câu',
        explanation: 'Câu này không có mẫu "... là ..." mà cho biết em làm gì, thích gì.',
      },
    ],
  },
  {
    subject: 'Tiếng Việt',
    weekNumber: 5,
    unit: VIET_UNIT_2,
    title: 'Từ ngữ chỉ người trong gia đình',
    difficulty: 1,
    questions: [
      {
        id: 'g2-tv-w05-q1',
        subject: 'Tiếng Việt',
        content: 'Người sinh ra mẹ em thì em gọi là gì?',
        options: ['Bà ngoại', 'Bà nội', 'Cô', 'Dì'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện từ và câu',
        explanation: 'Bên mẹ gọi là ngoại, bên bố gọi là nội.',
      },
      {
        id: 'g2-tv-w05-q2',
        subject: 'Tiếng Việt',
        content: 'Bố của bố em thì em gọi là gì?',
        options: ['Ông nội', 'Ông ngoại', 'Bác', 'Chú'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện từ và câu',
        explanation: 'Họ hàng bên bố là bên nội.',
      },
      {
        id: 'g2-tv-w05-q3',
        subject: 'Tiếng Việt',
        content: 'Từ nào chỉ người trong gia đình?',
        options: ['ông', 'bảng', 'ghế', 'mưa'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện từ và câu',
        explanation: 'Chỉ "ông" là người, ba từ còn lại là đồ vật và hiện tượng.',
      },
      {
        id: 'g2-tv-w05-q4',
        subject: 'Tiếng Việt',
        content: 'Em trai của mẹ em thì em gọi là gì?',
        options: ['Cậu', 'Chú', 'Bác', 'Dì'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện từ và câu',
        explanation: 'Em trai của mẹ gọi là cậu; em trai của bố mới gọi là chú.',
      },
      {
        id: 'g2-tv-w05-q5',
        subject: 'Tiếng Việt',
        content: 'Chọn từ điền vào chỗ trống: "Em rất ... ông bà."',
        options: ['kính yêu', 'chạy nhảy', 'màu xanh', 'cái bàn'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện từ và câu',
        explanation: 'Với người lớn tuổi, ta dùng từ thể hiện tình cảm và sự tôn trọng: kính yêu.',
      },
    ],
  },
  {
    subject: 'Tiếng Việt',
    weekNumber: 6,
    unit: VIET_UNIT_2,
    title: 'Tình cảm gia đình',
    difficulty: 1,
    questions: [
      {
        id: 'g2-tv-w06-q1',
        subject: 'Tiếng Việt',
        content: 'Mỗi tối bà thường làm gì cho Mai?',
        passage:
          'Mai sống cùng bà. Mỗi tối, bà kể chuyện cổ tích cho Mai nghe. Mai thương bà lắm.',
        options: ['Kể chuyện cổ tích', 'Nấu cơm', 'Đưa Mai đi học', 'Hát ru'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Tập đọc',
        explanation: 'Câu thứ hai nói rõ: "bà kể chuyện cổ tích cho Mai nghe".',
      },
      {
        id: 'g2-tv-w06-q2',
        subject: 'Tiếng Việt',
        content: 'Từ nào thể hiện tình cảm?',
        options: ['yêu thương', 'cái bàn', 'chạy nhanh', 'màu xanh'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện từ và câu',
        explanation: '"yêu thương" nói về cảm xúc trong lòng.',
      },
      {
        id: 'g2-tv-w06-q3',
        subject: 'Tiếng Việt',
        content: 'Câu nào thể hiện tình cảm với mẹ?',
        options: [
          'Em rất yêu mẹ.',
          'Mẹ đi làm lúc 7 giờ.',
          'Mẹ có một chiếc xe đạp.',
          'Mẹ em là công nhân.',
        ],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện từ và câu',
        explanation: 'Chỉ câu đầu nói lên tình cảm; các câu khác chỉ kể thông tin.',
      },
      {
        id: 'g2-tv-w06-q4',
        subject: 'Tiếng Việt',
        content: 'Việc nào thể hiện con biết giúp đỡ bố mẹ?',
        options: [
          'Quét nhà giúp mẹ',
          'Bày đồ chơi ra khắp phòng',
          'Xem tivi cả buổi',
          'Để bát chưa rửa trong bồn',
        ],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện từ và câu',
        explanation: 'Giúp việc nhà là cách thể hiện con ngoan và biết thương bố mẹ.',
      },
      {
        id: 'g2-tv-w06-q5',
        subject: 'Tiếng Việt',
        content: 'Câu "Mai thương bà lắm." có mấy tiếng?',
        options: ['4', '3', '5', '6'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện từ và câu',
        explanation: 'Đếm: Mai - thương - bà - lắm, tất cả 4 tiếng.',
      },
    ],
  },
];
