import type { WeekTopicSeed } from '../types';

/**
 * Lộ trình Lớp 1 — Toán và Tiếng Việt, tuần 1-6 (bộ Kết nối tri thức).
 *
 * 5 câu mỗi tuần. Cách soạn câu hỏi cho Lớp 1 khác hẳn các lớp trên:
 *
 *  - **Câu phải cực ngắn.** Học sinh Lớp 1 học kỳ I đang tập đọc từng tiếng, câu
 *    dài quá một dòng là các em bỏ giữa đường hoặc nhờ người lớn đọc hộ.
 *  - **Dùng emoji để đếm** thay vì viết "có ba quả táo": đề bài về số lượng mà
 *    đã viết số ra chữ thì không còn gì để đếm nữa.
 *  - **Không dùng thuật ngữ.** "Số liền sau" thì được (sách có dạy), nhưng
 *    "nguyên âm", "phụ âm" thì tránh — sách Lớp 1 gọi là "âm" và "vần".
 *
 * `id` mang tiền tố `g1-` để không bao giờ trùng với id của lớp khác;
 * `masteredQuestionIds` lưu trong AsyncStorage tham chiếu trực tiếp các id này.
 */

const MATH_UNIT_1 = 'Các số đến 10';
const MATH_UNIT_2 = 'Hình khối & Phép cộng, phép trừ trong phạm vi 5';

export const GRADE1_MATH_WEEKS: WeekTopicSeed[] = [
  {
    subject: 'Toán',
    weekNumber: 1,
    unit: MATH_UNIT_1,
    title: 'Các số 1, 2, 3',
    difficulty: 1,
    questions: [
      {
        id: 'g1-toan-w01-q1',
        subject: 'Toán',
        content: 'Có mấy quả táo? 🍎🍎',
        options: ['2', '1', '3', '4'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Đếm từng quả: một, hai. Có 2 quả táo.',
      },
      {
        id: 'g1-toan-w01-q2',
        subject: 'Toán',
        content: 'Có mấy ngôi sao? ⭐⭐⭐',
        options: ['3', '2', '4', '1'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Đếm: một, hai, ba. Có 3 ngôi sao.',
      },
      {
        id: 'g1-toan-w01-q3',
        subject: 'Toán',
        content: 'Trong ba số 1, 2, 3 số nào lớn nhất?',
        options: ['3', '1', '2', 'Bằng nhau'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Đếm càng về sau số càng lớn, nên 3 là số lớn nhất.',
      },
      {
        id: 'g1-toan-w01-q4',
        subject: 'Toán',
        content: 'Số liền sau số 1 là số nào?',
        options: ['2', '3', '1', '0'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Đếm 1 rồi tới 2, nên số liền sau số 1 là 2.',
      },
      {
        id: 'g1-toan-w01-q5',
        subject: 'Toán',
        content: 'Có 1 con mèo 🐱, thêm 1 con mèo nữa. Có mấy con mèo?',
        options: ['2', '1', '3', '4'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '1 con thêm 1 con là 2 con.',
      },
    ],
  },
  {
    subject: 'Toán',
    weekNumber: 2,
    unit: MATH_UNIT_1,
    title: 'Số 4, 5 và tách - gộp',
    difficulty: 1,
    questions: [
      {
        id: 'g1-toan-w02-q1',
        subject: 'Toán',
        content: 'Có mấy bông hoa? 🌸🌸🌸🌸',
        options: ['4', '3', '5', '2'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Đếm: một, hai, ba, bốn. Có 4 bông hoa.',
      },
      {
        id: 'g1-toan-w02-q2',
        subject: 'Toán',
        content: '5 gồm 4 và mấy?',
        options: ['1', '2', '3', '5'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '4 thêm 1 là 5, nên 5 gồm 4 và 1.',
      },
      {
        id: 'g1-toan-w02-q3',
        subject: 'Toán',
        content: '4 gồm 2 và mấy?',
        options: ['2', '1', '3', '4'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '2 thêm 2 là 4, nên 4 gồm 2 và 2.',
      },
      {
        id: 'g1-toan-w02-q4',
        subject: 'Toán',
        content: 'Số nào bé nhất: 4, 2, 5, 3?',
        options: ['2', '3', '4', '5'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Đếm 2, 3, 4, 5 — số đứng trước nhất là 2 nên 2 bé nhất.',
      },
      {
        id: 'g1-toan-w02-q5',
        subject: 'Toán',
        content: 'Gộp 3 và 2 được mấy?',
        options: ['5', '4', '6', '3'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '3 thêm 2 là 5.',
      },
    ],
  },
  {
    subject: 'Toán',
    weekNumber: 3,
    unit: MATH_UNIT_1,
    title: 'Hình khối đơn giản',
    difficulty: 1,
    questions: [
      {
        id: 'g1-toan-w03-q1',
        subject: 'Toán',
        content: 'Quả bóng ⚽ có dạng khối gì?',
        options: ['Khối cầu', 'Khối lập phương', 'Khối hộp chữ nhật', 'Khối trụ'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Quả bóng tròn lăn được mọi phía nên là khối cầu.',
      },
      {
        id: 'g1-toan-w03-q2',
        subject: 'Toán',
        content: 'Con xúc xắc 🎲 có sáu mặt đều là hình vuông. Đó là khối gì?',
        options: ['Khối lập phương', 'Khối cầu', 'Khối trụ', 'Khối hộp chữ nhật'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Khối có 6 mặt là hình vuông bằng nhau gọi là khối lập phương.',
      },
      {
        id: 'g1-toan-w03-q3',
        subject: 'Toán',
        content: 'Lon sữa 🥫 có dạng khối gì?',
        options: ['Khối trụ', 'Khối cầu', 'Khối lập phương', 'Khối hộp chữ nhật'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Hai đầu là hình tròn, thân thẳng đứng — đó là khối trụ.',
      },
      {
        id: 'g1-toan-w03-q4',
        subject: 'Toán',
        content: 'Hình nào có 3 cạnh?',
        options: ['Hình tam giác', 'Hình vuông', 'Hình tròn', 'Hình chữ nhật'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Tam giác có 3 cạnh; hình vuông và chữ nhật có 4 cạnh, hình tròn không có cạnh.',
      },
      {
        id: 'g1-toan-w03-q5',
        subject: 'Toán',
        content: 'Mặt đồng hồ 🕐 tròn là hình gì?',
        options: ['Hình tròn', 'Hình vuông', 'Hình tam giác', 'Hình chữ nhật'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Đường bao là một đường cong kín đều nên đó là hình tròn.',
      },
    ],
  },
  {
    subject: 'Toán',
    weekNumber: 4,
    unit: MATH_UNIT_1,
    title: 'Các số 6, 7, 8, 9, 10',
    difficulty: 1,
    questions: [
      {
        id: 'g1-toan-w04-q1',
        subject: 'Toán',
        content: 'Có mấy quả dâu? 🍓🍓🍓🍓🍓🍓🍓',
        options: ['7', '6', '8', '5'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Đếm lần lượt tới bảy. Có 7 quả dâu.',
      },
      {
        id: 'g1-toan-w04-q2',
        subject: 'Toán',
        content: 'Số liền trước số 10 là số nào?',
        options: ['9', '11', '8', '10'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Đếm 8, 9, 10 — số đứng ngay trước 10 là 9.',
      },
      {
        id: 'g1-toan-w04-q3',
        subject: 'Toán',
        content: 'Số nào lớn hơn: 8 hay 6?',
        options: ['8', '6', 'Bằng nhau', 'Không so được'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Trong dãy đếm, 8 đứng sau 6 nên 8 lớn hơn 6.',
      },
      {
        id: 'g1-toan-w04-q4',
        subject: 'Toán',
        content: 'Đếm tiếp: 6, 7, 8, ...?',
        options: ['9', '10', '7', '5'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Sau 8 là 9.',
      },
      {
        id: 'g1-toan-w04-q5',
        subject: 'Toán',
        content: 'Số 10 gồm mấy chục và mấy đơn vị?',
        options: ['1 chục và 0 đơn vị', '0 chục và 10 đơn vị', '10 chục và 0 đơn vị', '1 chục và 1 đơn vị'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Gộp 10 đơn vị lại được 1 chục, không còn đơn vị lẻ nào.',
      },
    ],
  },
  {
    subject: 'Toán',
    weekNumber: 5,
    unit: MATH_UNIT_2,
    title: 'Mấy và mấy',
    difficulty: 1,
    questions: [
      {
        id: 'g1-toan-w05-q1',
        subject: 'Toán',
        content: '7 gồm 5 và mấy?',
        options: ['2', '3', '1', '4'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '5 thêm 2 là 7.',
      },
      {
        id: 'g1-toan-w05-q2',
        subject: 'Toán',
        content: '10 gồm 6 và mấy?',
        options: ['4', '3', '5', '6'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '6 thêm 4 là 10.',
      },
      {
        id: 'g1-toan-w05-q3',
        subject: 'Toán',
        content: '8 gồm mấy và 3?',
        options: ['5', '4', '6', '3'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '5 thêm 3 là 8.',
      },
      {
        id: 'g1-toan-w05-q4',
        subject: 'Toán',
        content: '9 gồm 4 và mấy?',
        options: ['5', '4', '6', '3'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '4 thêm 5 là 9.',
      },
      {
        id: 'g1-toan-w05-q5',
        subject: 'Toán',
        content: 'Có 6 cái kẹo 🍬 chia đều cho 2 bạn. Vậy 6 gồm 3 và mấy?',
        options: ['3', '2', '4', '6'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Mỗi bạn 3 cái, hai phần bằng nhau: 6 gồm 3 và 3.',
      },
    ],
  },
  {
    subject: 'Toán',
    weekNumber: 6,
    unit: MATH_UNIT_2,
    title: 'Phép cộng, phép trừ trong phạm vi 5',
    difficulty: 1,
    questions: [
      {
        id: 'g1-toan-w06-q1',
        subject: 'Toán',
        content: '2 + 3 = ?',
        options: ['5', '4', '6', '1'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '2 thêm 3 là 5.',
      },
      {
        id: 'g1-toan-w06-q2',
        subject: 'Toán',
        content: '5 - 1 = ?',
        options: ['4', '3', '5', '6'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '5 bớt 1 còn 4.',
      },
      {
        id: 'g1-toan-w06-q3',
        subject: 'Toán',
        content: '4 - 2 = ?',
        options: ['2', '1', '3', '6'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '4 bớt 2 còn 2.',
      },
      {
        id: 'g1-toan-w06-q4',
        subject: 'Toán',
        content: '1 + 4 = ?',
        options: ['5', '4', '3', '6'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '1 thêm 4 là 5. Đổi chỗ hai số thì kết quả vẫn vậy.',
      },
      {
        id: 'g1-toan-w06-q5',
        subject: 'Toán',
        content: 'Có 5 con chim 🐦, bay đi 2 con. Còn lại mấy con?',
        options: ['3', '2', '4', '7'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Bay đi thì làm phép trừ: 5 - 2 = 3 con.',
      },
    ],
  },
];

const VIET_UNIT_1 = 'Làm quen với âm và chữ';
const VIET_UNIT_2 = 'Dấu thanh, vần và tập đọc';

export const GRADE1_VIETNAMESE_WEEKS: WeekTopicSeed[] = [
  {
    subject: 'Tiếng Việt',
    weekNumber: 1,
    unit: VIET_UNIT_1,
    title: 'Âm a, b, c, e',
    difficulty: 1,
    questions: [
      {
        id: 'g1-tv-w01-q1',
        subject: 'Tiếng Việt',
        content: 'Tiếng "ba" gồm âm b và âm nào?',
        options: ['a', 'e', 'c', 'b'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện đọc',
        explanation: 'Đọc chậm "b - a - ba": âm đứng sau là a.',
      },
      {
        id: 'g1-tv-w01-q2',
        subject: 'Tiếng Việt',
        content: 'Tiếng nào bắt đầu bằng âm b?',
        options: ['bà', 'cá', 'e', 'an'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện đọc',
        explanation: 'Chỉ "bà" mở đầu bằng âm b.',
      },
      {
        id: 'g1-tv-w01-q3',
        subject: 'Tiếng Việt',
        content: 'Tiếng "ca" có âm đầu là âm nào?',
        options: ['c', 'a', 'k', 'b'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện đọc',
        explanation: 'Âm đầu là âm đứng trước: "c - a - ca".',
      },
      {
        id: 'g1-tv-w01-q4',
        subject: 'Tiếng Việt',
        content: 'Từ "bé" có mấy tiếng?',
        options: ['1', '2', '3', '4'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện từ và câu',
        explanation: 'Đọc một hơi là xong nên "bé" chỉ có 1 tiếng.',
      },
      {
        id: 'g1-tv-w01-q5',
        subject: 'Tiếng Việt',
        content: 'Tiếng nào có âm e?',
        options: ['bé', 'ba', 'cô', 'cá'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện đọc',
        explanation: '"bé" gồm âm b và âm e.',
      },
    ],
  },
  {
    subject: 'Tiếng Việt',
    weekNumber: 2,
    unit: VIET_UNIT_1,
    title: 'Âm o, ô, ơ, d, đ, ê',
    difficulty: 1,
    questions: [
      {
        id: 'g1-tv-w02-q1',
        subject: 'Tiếng Việt',
        content: 'Tiếng "cô" có âm chính là âm nào?',
        options: ['ô', 'o', 'ơ', 'c'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện đọc',
        explanation: '"c - ô - cô": âm chính là ô, có dấu mũ.',
      },
      {
        id: 'g1-tv-w02-q2',
        subject: 'Tiếng Việt',
        content: 'Tiếng nào bắt đầu bằng âm đ?',
        options: ['đò', 'cò', 'bò', 'hồ'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện đọc',
        explanation: 'Chữ đ có gạch ngang; "đò" mở đầu bằng âm đ.',
      },
      {
        id: 'g1-tv-w02-q3',
        subject: 'Tiếng Việt',
        content: 'Tiếng "dê" gồm âm d và âm nào?',
        options: ['ê', 'e', 'đ', 'ơ'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện đọc',
        explanation: '"d - ê - dê": âm sau là ê.',
      },
      {
        id: 'g1-tv-w02-q4',
        subject: 'Tiếng Việt',
        content: 'Tiếng "bơ" có âm chính là âm nào?',
        options: ['ơ', 'o', 'ô', 'b'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện đọc',
        explanation: 'Chữ ơ có dấu râu bên phải.',
      },
      {
        id: 'g1-tv-w02-q5',
        subject: 'Tiếng Việt',
        content: 'Tiếng nào có âm o?',
        options: ['bò', 'bê', 'bà', 'bí'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện đọc',
        explanation: '"bò" gồm âm b và âm o.',
      },
    ],
  },
  {
    subject: 'Tiếng Việt',
    weekNumber: 3,
    unit: VIET_UNIT_2,
    title: 'Các dấu thanh',
    difficulty: 1,
    questions: [
      {
        id: 'g1-tv-w03-q1',
        subject: 'Tiếng Việt',
        content: 'Tiếng "mẹ" mang dấu thanh gì?',
        options: ['Dấu nặng', 'Dấu huyền', 'Dấu sắc', 'Dấu hỏi'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Chính tả',
        explanation: 'Dấu nặng là một dấu chấm đặt dưới chữ.',
      },
      {
        id: 'g1-tv-w03-q2',
        subject: 'Tiếng Việt',
        content: 'Tiếng "bà" mang dấu thanh gì?',
        options: ['Dấu huyền', 'Dấu sắc', 'Dấu ngã', 'Dấu nặng'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Chính tả',
        explanation: 'Dấu huyền là nét gạch chéo xuống, đọc giọng thấp.',
      },
      {
        id: 'g1-tv-w03-q3',
        subject: 'Tiếng Việt',
        content: 'Tiếng "cá" mang dấu thanh gì?',
        options: ['Dấu sắc', 'Dấu huyền', 'Dấu hỏi', 'Dấu ngã'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Chính tả',
        explanation: 'Dấu sắc là nét gạch chéo lên, đọc giọng cao.',
      },
      {
        id: 'g1-tv-w03-q4',
        subject: 'Tiếng Việt',
        content: 'Tiếng "mũ" mang dấu thanh gì?',
        options: ['Dấu ngã', 'Dấu hỏi', 'Dấu sắc', 'Dấu nặng'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Chính tả',
        explanation: 'Dấu ngã là nét uốn lượn đặt trên chữ.',
      },
      {
        id: 'g1-tv-w03-q5',
        subject: 'Tiếng Việt',
        content: 'Tiếng "bảng" mang dấu thanh gì?',
        options: ['Dấu hỏi', 'Dấu ngã', 'Dấu huyền', 'Dấu sắc'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Chính tả',
        explanation: 'Dấu hỏi trông như một cái móc nhỏ đặt trên chữ.',
      },
    ],
  },
  {
    subject: 'Tiếng Việt',
    weekNumber: 4,
    unit: VIET_UNIT_2,
    title: 'Âm i, k, l, m, n',
    difficulty: 1,
    questions: [
      {
        id: 'g1-tv-w04-q1',
        subject: 'Tiếng Việt',
        content: 'Tiếng "kê" có âm đầu là âm nào?',
        options: ['k', 'c', 'ê', 'l'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện đọc',
        explanation: '"k - ê - kê": âm đầu là k.',
      },
      {
        id: 'g1-tv-w04-q2',
        subject: 'Tiếng Việt',
        content: 'Âm k thường đứng trước những âm nào?',
        options: ['i, e, ê', 'a, o, u', 'ơ, ô, ư', 'y, a, o'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Chính tả',
        explanation: 'Ta viết kê, kí, kẻ; còn trước a, o, u thì viết c: ca, co, cu.',
      },
      {
        id: 'g1-tv-w04-q3',
        subject: 'Tiếng Việt',
        content: 'Tiếng nào bắt đầu bằng âm l?',
        options: ['lá', 'nó', 'mẹ', 'kí'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện đọc',
        explanation: 'Chỉ "lá" mở đầu bằng âm l.',
      },
      {
        id: 'g1-tv-w04-q4',
        subject: 'Tiếng Việt',
        content: 'Tiếng "nụ" có âm đầu là âm nào?',
        options: ['n', 'm', 'l', 'u'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện đọc',
        explanation: '"n - ụ - nụ": âm đầu là n.',
      },
      {
        id: 'g1-tv-w04-q5',
        subject: 'Tiếng Việt',
        content: 'Tiếng "mì" có âm chính là âm nào?',
        options: ['i', 'm', 'ì', 'y'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện đọc',
        explanation: '"m - ì - mì": âm chính là i, mang dấu huyền.',
      },
    ],
  },
  {
    subject: 'Tiếng Việt',
    weekNumber: 5,
    unit: VIET_UNIT_2,
    title: 'Vần đơn giản: an, at, am, ap',
    difficulty: 1,
    questions: [
      {
        id: 'g1-tv-w05-q1',
        subject: 'Tiếng Việt',
        content: 'Tiếng "lan" có vần gì?',
        options: ['an', 'am', 'at', 'ang'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện đọc',
        explanation: 'Bỏ âm đầu l ra, phần còn lại là vần an.',
      },
      {
        id: 'g1-tv-w05-q2',
        subject: 'Tiếng Việt',
        content: 'Tiếng "cát" có vần gì?',
        options: ['at', 'an', 'ac', 'ap'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện đọc',
        explanation: 'Bỏ âm đầu c ra, còn lại vần at.',
      },
      {
        id: 'g1-tv-w05-q3',
        subject: 'Tiếng Việt',
        content: 'Tiếng nào có vần am?',
        options: ['cam', 'can', 'cát', 'cân'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện đọc',
        explanation: '"cam" gồm âm c và vần am.',
      },
      {
        id: 'g1-tv-w05-q4',
        subject: 'Tiếng Việt',
        content: 'Tiếng "nắp" có vần gì?',
        options: ['ap', 'am', 'an', 'at'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện đọc',
        explanation: 'Bỏ âm đầu n và dấu sắc, phần còn lại là vần ap.',
      },
      {
        id: 'g1-tv-w05-q5',
        subject: 'Tiếng Việt',
        content: 'Vần an gồm âm a và âm nào?',
        options: ['n', 'm', 't', 'p'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện đọc',
        explanation: 'Đọc chậm "a - n - an".',
      },
    ],
  },
  {
    subject: 'Tiếng Việt',
    weekNumber: 6,
    unit: VIET_UNIT_2,
    title: 'Đọc từ và câu ngắn',
    difficulty: 1,
    questions: [
      {
        id: 'g1-tv-w06-q1',
        subject: 'Tiếng Việt',
        content: 'Câu "Bé Hà đi học." có mấy tiếng?',
        options: ['4', '3', '5', '2'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện từ và câu',
        explanation: 'Đếm từng tiếng: Bé - Hà - đi - học, tất cả 4 tiếng.',
      },
      {
        id: 'g1-tv-w06-q2',
        subject: 'Tiếng Việt',
        content: 'Câu "Mẹ nấu cơm." kết thúc bằng dấu gì?',
        options: ['Dấu chấm', 'Dấu phẩy', 'Dấu chấm hỏi', 'Dấu hai chấm'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện từ và câu',
        explanation: 'Câu kể chuyện bình thường thì kết thúc bằng dấu chấm.',
      },
      {
        id: 'g1-tv-w06-q3',
        subject: 'Tiếng Việt',
        content: 'Chữ đầu câu phải viết như thế nào?',
        options: ['Viết hoa', 'Viết thường', 'Viết nhỏ hơn', 'Viết in nghiêng'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Chính tả',
        explanation: 'Chữ đầu câu luôn viết hoa để người đọc biết câu mới bắt đầu.',
      },
      {
        id: 'g1-tv-w06-q4',
        subject: 'Tiếng Việt',
        content: 'Con mèo thích làm gì?',
        passage: 'Nhà em có một con mèo. Mèo rất thích bắt chuột.',
        options: ['Bắt chuột', 'Bắt cá', 'Trèo cây', 'Ngủ trên giường'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Tập đọc',
        explanation: 'Câu thứ hai nói rõ: "Mèo rất thích bắt chuột."',
      },
      {
        id: 'g1-tv-w06-q5',
        subject: 'Tiếng Việt',
        content: 'Từ "con mèo" gồm mấy tiếng?',
        options: ['2', '1', '3', '4'],
        correctAnswer: 0,
        rewardMinutes: 2,
        skill: 'Luyện từ và câu',
        explanation: 'Hai tiếng: "con" và "mèo".',
      },
    ],
  },
];
