import type { WeekTopicSeed } from '../types';

/**
 * Lộ trình Lớp 5 — Toán và Tiếng Việt, tuần 1-6 (bộ Kết nối tri thức).
 *
 * 5 câu mỗi tuần, `difficulty: 3` nên hoàn thành một tuần được 6 phút thưởng.
 *
 * Quy ước viết số ở đây: **dấu phẩy là dấu thập phân** (0,25) và phân số viết
 * dạng `a/b` trên một dòng. Không dùng dấu phẩy để nhóm chữ số nghìn như tiếng
 * Anh — với học sinh Việt Nam thì "1,5" phải đọc là "một phẩy năm", nhóm nghìn
 * bằng dấu phẩy sẽ gây đọc sai ngay ở chương số thập phân.
 *
 * Ghi chú về đáp án: đáp án đúng luôn ở vị trí đầu trong tệp dữ liệu;
 * `shuffleQuestionOptions` trộn lại thứ tự mỗi lần tạo đề.
 */

const MATH_UNIT_1 = 'Phân số, hỗn số & số thập phân';
const MATH_UNIT_2 = 'Hàng số thập phân, số đo & phép cộng';

export const GRADE5_MATH_WEEKS: WeekTopicSeed[] = [
  {
    subject: 'Toán',
    weekNumber: 1,
    unit: MATH_UNIT_1,
    title: 'Phân số và phân số thập phân',
    difficulty: 3,
    questions: [
      {
        id: 'g5-toan-w01-q1',
        subject: 'Toán',
        content: 'Phân số thập phân là phân số có mẫu số là gì?',
        options: [
          '10, 100, 1000, ...',
          'Một số lẻ bất kì',
          'Luôn bằng 1',
          'Một số nguyên tố',
        ],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Mẫu số phải là 10 hoặc lũy thừa của 10 thì mới gọi là phân số thập phân.',
      },
      {
        id: 'g5-toan-w01-q2',
        subject: 'Toán',
        content: 'Phân số nào là phân số thập phân?',
        options: ['3/10', '3/7', '5/6', '2/9'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Chỉ 3/10 có mẫu số là 10.',
      },
      {
        id: 'g5-toan-w01-q3',
        subject: 'Toán',
        content: 'Rút gọn phân số 6/8 được phân số nào?',
        options: ['3/4', '2/3', '6/4', '1/2'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Chia cả tử và mẫu cho 2: 6:2 = 3, 8:2 = 4.',
      },
      {
        id: 'g5-toan-w01-q4',
        subject: 'Toán',
        content: 'Viết 3/5 thành phân số thập phân.',
        options: ['6/10', '3/10', '5/10', '30/10'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Nhân cả tử và mẫu với 2: 3×2 = 6, 5×2 = 10.',
      },
      {
        id: 'g5-toan-w01-q5',
        subject: 'Toán',
        content: 'So sánh 2/3 và 3/4.',
        options: ['2/3 < 3/4', '2/3 > 3/4', '2/3 = 3/4', 'Không so sánh được'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Quy đồng mẫu số 12: 2/3 = 8/12 và 3/4 = 9/12, mà 8 < 9.',
      },
    ],
  },
  {
    subject: 'Toán',
    weekNumber: 2,
    unit: MATH_UNIT_1,
    title: 'Hỗn số',
    difficulty: 3,
    questions: [
      {
        id: 'g5-toan-w02-q1',
        subject: 'Toán',
        content: 'Hỗn số 2 1/4 đọc như thế nào?',
        options: [
          'Hai và một phần tư',
          'Hai mươi mốt phần tư',
          'Hai một bốn',
          'Hai phần tư',
        ],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Đọc phần nguyên, thêm chữ "và", rồi đọc phần phân số.',
      },
      {
        id: 'g5-toan-w02-q2',
        subject: 'Toán',
        content: 'Chuyển hỗn số 2 1/3 thành phân số.',
        options: ['7/3', '5/3', '6/3', '2/3'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Lấy phần nguyên nhân mẫu rồi cộng tử: 2×3 + 1 = 7, giữ mẫu 3.',
      },
      {
        id: 'g5-toan-w02-q3',
        subject: 'Toán',
        content: 'Chuyển phân số 9/4 thành hỗn số.',
        options: ['2 1/4', '1 5/4', '2 3/4', '4 1/9'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: '9 : 4 = 2 dư 1, nên phần nguyên là 2 và phần phân số là 1/4.',
      },
      {
        id: 'g5-toan-w02-q4',
        subject: 'Toán',
        content: 'Phần phân số của một hỗn số luôn có tính chất gì?',
        options: [
          'Bé hơn 1',
          'Lớn hơn 1',
          'Bằng 1',
          'Bằng phần nguyên',
        ],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Nếu phần phân số lớn hơn hoặc bằng 1 thì phải chuyển bớt sang phần nguyên.',
      },
      {
        id: 'g5-toan-w02-q5',
        subject: 'Toán',
        content: 'Hỗn số 3 2/5 bằng phân số nào?',
        options: ['17/5', '15/5', '11/5', '32/5'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: '3×5 + 2 = 17, giữ nguyên mẫu 5.',
      },
    ],
  },
  {
    subject: 'Toán',
    weekNumber: 3,
    unit: MATH_UNIT_1,
    title: 'Khái niệm số thập phân',
    difficulty: 3,
    questions: [
      {
        id: 'g5-toan-w03-q1',
        subject: 'Toán',
        content: 'Số 0,1 đọc như thế nào?',
        options: [
          'Không phẩy một',
          'Không một',
          'Một phẩy không',
          'Một phần không',
        ],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Đọc phần nguyên, đọc "phẩy", rồi đọc phần thập phân.',
      },
      {
        id: 'g5-toan-w03-q2',
        subject: 'Toán',
        content: 'Phân số 7/10 viết dưới dạng số thập phân là gì?',
        options: ['0,7', '7,0', '0,07', '7,10'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Mẫu số 10 thì phần thập phân có một chữ số: 0,7.',
      },
      {
        id: 'g5-toan-w03-q3',
        subject: 'Toán',
        content: 'Số 3,25 có phần nguyên là bao nhiêu?',
        options: ['3', '25', '325', '0'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Phần nguyên là phần đứng trước dấu phẩy.',
      },
      {
        id: 'g5-toan-w03-q4',
        subject: 'Toán',
        content: '5 cm bằng bao nhiêu mét?',
        options: ['0,05 m', '0,5 m', '5 m', '50 m'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: '1 m = 100 cm nên 5 cm = 5/100 m = 0,05 m.',
      },
      {
        id: 'g5-toan-w03-q5',
        subject: 'Toán',
        content: 'Số thập phân 0,001 bằng phân số nào?',
        options: ['1/1000', '1/100', '1/10', '1/10000'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Phần thập phân có 3 chữ số nên mẫu số là 1000.',
      },
    ],
  },
  {
    subject: 'Toán',
    weekNumber: 4,
    unit: MATH_UNIT_2,
    title: 'Hàng của số thập phân, so sánh',
    difficulty: 3,
    questions: [
      {
        id: 'g5-toan-w04-q1',
        subject: 'Toán',
        content: 'Trong số 4,725 chữ số 2 thuộc hàng nào?',
        options: [
          'Hàng phần trăm',
          'Hàng phần mười',
          'Hàng phần nghìn',
          'Hàng chục',
        ],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Sau dấu phẩy lần lượt là phần mười (7), phần trăm (2), phần nghìn (5).',
      },
      {
        id: 'g5-toan-w04-q2',
        subject: 'Toán',
        content: 'So sánh 8,1 và 8,09.',
        options: ['8,1 > 8,09', '8,1 < 8,09', '8,1 = 8,09', 'Không so sánh được'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Phần nguyên bằng nhau; so hàng phần mười: 1 > 0 nên 8,1 lớn hơn.',
      },
      {
        id: 'g5-toan-w04-q3',
        subject: 'Toán',
        content: 'Số nào lớn nhất: 0,9 ; 0,89 ; 0,899 ; 0,8?',
        options: ['0,9', '0,899', '0,89', '0,8'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'So hàng phần mười trước: 9 lớn hơn 8, nên 0,9 lớn nhất.',
      },
      {
        id: 'g5-toan-w04-q4',
        subject: 'Toán',
        content: 'Viết 0,5 thành 0,50 thì giá trị của số thay đổi thế nào?',
        options: [
          'Không đổi',
          'Tăng lên 10 lần',
          'Giảm đi 10 lần',
          'Tăng thêm 0,45',
        ],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Thêm chữ số 0 vào bên phải phần thập phân không làm đổi giá trị.',
      },
      {
        id: 'g5-toan-w04-q5',
        subject: 'Toán',
        content: 'Sắp xếp 3,2 ; 3,02 ; 3,22 theo thứ tự từ bé đến lớn.',
        options: [
          '3,02 ; 3,2 ; 3,22',
          '3,2 ; 3,02 ; 3,22',
          '3,22 ; 3,2 ; 3,02',
          '3,02 ; 3,22 ; 3,2',
        ],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Viết cùng số chữ số: 3,20 ; 3,02 ; 3,22 → nhỏ nhất là 3,02.',
      },
    ],
  },
  {
    subject: 'Toán',
    weekNumber: 5,
    unit: MATH_UNIT_2,
    title: 'Viết số đo độ dài, khối lượng dạng thập phân',
    difficulty: 3,
    questions: [
      {
        id: 'g5-toan-w05-q1',
        subject: 'Toán',
        content: '3 m 5 cm bằng bao nhiêu mét?',
        options: ['3,05 m', '3,5 m', '35 m', '3,005 m'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: '5 cm = 0,05 m nên tổng là 3,05 m.',
      },
      {
        id: 'g5-toan-w05-q2',
        subject: 'Toán',
        content: '7 kg 250 g bằng bao nhiêu ki-lô-gam?',
        options: ['7,25 kg', '7,250 kg', '7,025 kg', '72,5 kg'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: '1 kg = 1000 g nên 250 g = 0,25 kg; tổng là 7,25 kg.',
      },
      {
        id: 'g5-toan-w05-q3',
        subject: 'Toán',
        content: '2 km 500 m bằng bao nhiêu ki-lô-mét?',
        options: ['2,5 km', '2,05 km', '25 km', '2,500 km'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: '1 km = 1000 m nên 500 m = 0,5 km.',
      },
      {
        id: 'g5-toan-w05-q4',
        subject: 'Toán',
        content: '0,4 tấn bằng bao nhiêu ki-lô-gam?',
        options: ['400 kg', '40 kg', '4 000 kg', '4 kg'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: '1 tấn = 1000 kg nên 0,4 tấn = 0,4 × 1000 = 400 kg.',
      },
      {
        id: 'g5-toan-w05-q5',
        subject: 'Toán',
        content: '12,5 dm bằng bao nhiêu xăng-ti-mét?',
        options: ['125 cm', '12,5 cm', '1 250 cm', '1,25 cm'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: '1 dm = 10 cm nên 12,5 dm = 12,5 × 10 = 125 cm.',
      },
    ],
  },
  {
    subject: 'Toán',
    weekNumber: 6,
    unit: MATH_UNIT_2,
    title: 'Cộng hai số thập phân',
    difficulty: 3,
    questions: [
      {
        id: 'g5-toan-w06-q1',
        subject: 'Toán',
        content: '3,5 + 2,4 = ?',
        options: ['5,9', '5,09', '6,9', '59'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Cộng phần thập phân 5 + 4 = 9, phần nguyên 3 + 2 = 5.',
      },
      {
        id: 'g5-toan-w06-q2',
        subject: 'Toán',
        content: '12,7 + 8,35 = ?',
        options: ['21,05', '20,05', '21,5', '20,42'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Viết 12,70 + 8,35: 70 + 35 = 105 phần trăm, nhớ 1 → 21,05.',
      },
      {
        id: 'g5-toan-w06-q3',
        subject: 'Toán',
        content: '0,25 + 0,75 = ?',
        options: ['1', '0,9', '0,100', '1,1'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: '25 + 75 = 100 phần trăm, đúng bằng 1 đơn vị.',
      },
      {
        id: 'g5-toan-w06-q4',
        subject: 'Toán',
        content: 'Khi đặt tính cộng hai số thập phân, ta phải làm gì?',
        options: [
          'Viết dấu phẩy thẳng cột với nhau',
          'Bỏ dấu phẩy rồi cộng như số tự nhiên',
          'Viết hai số thẳng lề phải',
          'Cộng phần nguyên trước rồi ghép phần thập phân',
        ],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Dấu phẩy thẳng cột thì các hàng cùng loại mới thẳng nhau.',
      },
      {
        id: 'g5-toan-w06-q5',
        subject: 'Toán',
        content: 'Thùng thứ nhất có 5,2 l dầu, thùng thứ hai có 4,85 l. Cả hai thùng có bao nhiêu lít?',
        options: ['10,05 l', '9,05 l', '10,5 l', '9,37 l'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: '5,20 + 4,85 = 10,05 l.',
      },
    ],
  },
];

const VIET_UNIT_1 = 'Từ đồng nghĩa, trái nghĩa, nhiều nghĩa';
const VIET_UNIT_2 = 'Từ ngữ về thiên nhiên & đại từ';

export const GRADE5_VIETNAMESE_WEEKS: WeekTopicSeed[] = [
  {
    subject: 'Tiếng Việt',
    weekNumber: 1,
    unit: VIET_UNIT_1,
    title: 'Từ đồng nghĩa - Chủ điểm Tổ quốc',
    difficulty: 3,
    questions: [
      {
        id: 'g5-tv-w01-q1',
        subject: 'Tiếng Việt',
        content: 'Từ đồng nghĩa là những từ như thế nào?',
        options: [
          'Có nghĩa giống nhau hoặc gần giống nhau',
          'Có nghĩa trái ngược nhau',
          'Đọc giống nhau nhưng nghĩa khác nhau',
          'Có nhiều nghĩa khác nhau',
        ],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: 'Ví dụ: siêng năng - chăm chỉ - cần cù.',
      },
      {
        id: 'g5-tv-w01-q2',
        subject: 'Tiếng Việt',
        content: 'Từ nào đồng nghĩa với "Tổ quốc"?',
        options: ['đất nước', 'thành phố', 'thôn xóm', 'gia đình'],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: '"đất nước", "quốc gia", "non sông" đều đồng nghĩa với Tổ quốc.',
      },
      {
        id: 'g5-tv-w01-q3',
        subject: 'Tiếng Việt',
        content: 'Từ nào KHÔNG đồng nghĩa với "to"?',
        options: ['bé', 'lớn', 'khổng lồ', 'vĩ đại'],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: '"bé" là từ trái nghĩa, ba từ còn lại đều cùng nghĩa với "to".',
      },
      {
        id: 'g5-tv-w01-q4',
        subject: 'Tiếng Việt',
        content: 'Từ nào đồng nghĩa với "siêng năng"?',
        options: ['chăm chỉ', 'lười nhác', 'chậm chạp', 'vội vàng'],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: '"chăm chỉ" và "siêng năng" cùng chỉ tính hay làm việc.',
      },
      {
        id: 'g5-tv-w01-q5',
        subject: 'Tiếng Việt',
        content: 'Từ nào đồng nghĩa với "quê hương"?',
        options: ['quê cha đất tổ', 'nước ngoài', 'thành thị', 'lữ khách'],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: '"quê cha đất tổ", "quê quán", "nơi chôn rau cắt rốn" cùng chỉ quê hương.',
      },
    ],
  },
  {
    subject: 'Tiếng Việt',
    weekNumber: 2,
    unit: VIET_UNIT_1,
    title: 'Từ trái nghĩa',
    difficulty: 3,
    questions: [
      {
        id: 'g5-tv-w02-q1',
        subject: 'Tiếng Việt',
        content: 'Từ trái nghĩa với "hoà bình" là từ nào?',
        options: ['chiến tranh', 'yên ổn', 'thanh bình', 'êm đềm'],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: 'Ba từ còn lại đều đồng nghĩa với hoà bình.',
      },
      {
        id: 'g5-tv-w02-q2',
        subject: 'Tiếng Việt',
        content: 'Cặp nào là cặp từ trái nghĩa?',
        options: ['cao / thấp', 'cao / lớn', 'to / khổng lồ', 'nhanh / lẹ'],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: 'Ba cặp còn lại là từ đồng nghĩa.',
      },
      {
        id: 'g5-tv-w02-q3',
        subject: 'Tiếng Việt',
        content: 'Trong câu thành ngữ "Gạn đục khơi trong", cặp từ trái nghĩa là gì?',
        options: ['đục / trong', 'gạn / khơi', 'gạn / trong', 'đục / khơi'],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: '"đục" và "trong" nói về hai trạng thái ngược nhau của nước.',
      },
      {
        id: 'g5-tv-w02-q4',
        subject: 'Tiếng Việt',
        content: 'Từ trái nghĩa với "thắng" là từ nào?',
        options: ['thua', 'hơn', 'giành', 'đạt'],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: 'Thắng - thua là một cặp trái nghĩa quen thuộc.',
      },
      {
        id: 'g5-tv-w02-q5',
        subject: 'Tiếng Việt',
        content: 'Từ trái nghĩa có tác dụng gì trong câu?',
        options: [
          'Làm nổi bật sự đối lập',
          'Làm câu dài hơn',
          'Thay thế cho dấu câu',
          'Giúp câu đúng ngữ pháp',
        ],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: 'Đặt hai từ ngược nghĩa cạnh nhau khiến ý cần nhấn mạnh rõ hơn.',
      },
    ],
  },
  {
    subject: 'Tiếng Việt',
    weekNumber: 3,
    unit: VIET_UNIT_1,
    title: 'Từ nhiều nghĩa',
    difficulty: 3,
    questions: [
      {
        id: 'g5-tv-w03-q1',
        subject: 'Tiếng Việt',
        content: 'Từ nhiều nghĩa là từ như thế nào?',
        options: [
          'Có một nghĩa gốc và một hay nhiều nghĩa chuyển',
          'Có nghĩa trái ngược nhau',
          'Đọc giống nhau nhưng nghĩa hoàn toàn khác nhau',
          'Chỉ có duy nhất một nghĩa',
        ],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: 'Các nghĩa của từ nhiều nghĩa luôn có liên hệ với nhau.',
      },
      {
        id: 'g5-tv-w03-q2',
        subject: 'Tiếng Việt',
        content: 'Trong "mũi thuyền", từ "mũi" được dùng theo nghĩa nào?',
        options: ['Nghĩa chuyển', 'Nghĩa gốc', 'Nghĩa trái ngược', 'Không có nghĩa'],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: 'Nghĩa gốc của "mũi" là bộ phận trên mặt người; mũi thuyền là phần nhọn phía trước.',
      },
      {
        id: 'g5-tv-w03-q3',
        subject: 'Tiếng Việt',
        content: 'Từ "chân" trong "chân núi" mang nghĩa gì?',
        options: ['Nghĩa chuyển', 'Nghĩa gốc', 'Nghĩa đồng âm', 'Nghĩa trái ngược'],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: 'Chân núi là phần dưới cùng của núi, chuyển từ nghĩa "chân người".',
      },
      {
        id: 'g5-tv-w03-q4',
        subject: 'Tiếng Việt',
        content: 'Nghĩa gốc của từ "mắt" là gì?',
        options: [
          'Bộ phận để nhìn của người và động vật',
          'Chỗ lồi lên trên thân cây tre',
          'Lỗ nhỏ trên tấm lưới',
          'Điểm giao nhau của hai đường',
        ],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: 'Ba nghĩa còn lại đều là nghĩa chuyển: mắt tre, mắt lưới, mắt bão.',
      },
      {
        id: 'g5-tv-w03-q5',
        subject: 'Tiếng Việt',
        content: 'Trong câu "Bé bị đau chân.", từ "chân" dùng theo nghĩa nào?',
        options: ['Nghĩa gốc', 'Nghĩa chuyển', 'Nghĩa đồng âm', 'Nghĩa trái ngược'],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: 'Đây là chân của con người, đúng nghĩa ban đầu của từ.',
      },
    ],
  },
  {
    subject: 'Tiếng Việt',
    weekNumber: 4,
    unit: VIET_UNIT_1,
    title: 'Luyện tập về từ nhiều nghĩa',
    difficulty: 3,
    questions: [
      {
        id: 'g5-tv-w04-q1',
        subject: 'Tiếng Việt',
        content: '"Đường" trong "đường phố" và "đường" trong "đường ăn" là hiện tượng gì?',
        options: [
          'Từ đồng âm',
          'Từ nhiều nghĩa',
          'Từ đồng nghĩa',
          'Từ trái nghĩa',
        ],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: 'Hai nghĩa này không liên hệ gì với nhau, chỉ trùng cách đọc — đó là từ đồng âm.',
      },
      {
        id: 'g5-tv-w04-q2',
        subject: 'Tiếng Việt',
        content: 'Trong "ăn ảnh", từ "ăn" dùng theo nghĩa nào?',
        options: ['Nghĩa chuyển', 'Nghĩa gốc', 'Nghĩa đồng âm', 'Nghĩa trái ngược'],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: 'Nghĩa gốc của "ăn" là đưa thức ăn vào miệng; "ăn ảnh" là nghĩa chuyển.',
      },
      {
        id: 'g5-tv-w04-q3',
        subject: 'Tiếng Việt',
        content: 'Từ "cổ" trong "cổ áo" mang nghĩa nào?',
        options: ['Nghĩa chuyển', 'Nghĩa gốc', 'Nghĩa đồng âm', 'Nghĩa đồng nghĩa'],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: 'Cổ áo là phần áo ở vị trí cái cổ — chuyển từ nghĩa bộ phận cơ thể.',
      },
      {
        id: 'g5-tv-w04-q4',
        subject: 'Tiếng Việt',
        content: 'Câu nào dùng từ "lưng" theo nghĩa chuyển?',
        options: [
          'Lưng đồi phủ đầy hoa.',
          'Bé bị đau lưng.',
          'Em xoa lưng cho bà.',
          'Anh ấy có tấm lưng rộng.',
        ],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: 'Ba câu còn lại đều nói về lưng người, tức nghĩa gốc.',
      },
      {
        id: 'g5-tv-w04-q5',
        subject: 'Tiếng Việt',
        content: 'Muốn phân biệt từ nhiều nghĩa với từ đồng âm, ta xét điều gì?',
        options: [
          'Các nghĩa có liên hệ với nhau hay không',
          'Từ đó dài hay ngắn',
          'Từ đó là danh từ hay động từ',
          'Từ đó có dấu thanh gì',
        ],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: 'Có liên hệ thì là từ nhiều nghĩa; hoàn toàn không liên quan thì là từ đồng âm.',
      },
    ],
  },
  {
    subject: 'Tiếng Việt',
    weekNumber: 5,
    unit: VIET_UNIT_2,
    title: 'Từ ngữ về thiên nhiên',
    difficulty: 3,
    questions: [
      {
        id: 'g5-tv-w05-q1',
        subject: 'Tiếng Việt',
        content: 'Từ nào chỉ sự vật của thiên nhiên?',
        options: ['thác nước', 'cặp sách', 'xe đạp', 'quyển vở'],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: 'Ba từ còn lại là vật do con người làm ra.',
      },
      {
        id: 'g5-tv-w05-q2',
        subject: 'Tiếng Việt',
        content: 'Thành ngữ "Lên thác xuống ghềnh" nói về điều gì?',
        options: [
          'Cuộc sống gian nan, vất vả',
          'Phong cảnh rất đẹp',
          'Đi du lịch xa',
          'Nước chảy rất êm',
        ],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: 'Thác và ghềnh đều là chỗ nước chảy dữ, ý chỉ nỗi khó khăn phải trải qua.',
      },
      {
        id: 'g5-tv-w05-q3',
        subject: 'Tiếng Việt',
        content: 'Từ nào tả tiếng nước chảy?',
        options: ['róc rách', 'chói chang', 'ngào ngạt', 'mềm mại'],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: '"róc rách" là từ tả âm thanh của dòng nước nhỏ.',
      },
      {
        id: 'g5-tv-w05-q4',
        subject: 'Tiếng Việt',
        content: 'Bốn mùa trong năm gồm những mùa nào?',
        options: [
          'Xuân, hạ, thu, đông',
          'Xuân, hạ, mưa, nắng',
          'Nắng, mưa, gió, bão',
          'Sáng, trưa, chiều, tối',
        ],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: 'Bốn mùa lần lượt là xuân, hạ (hè), thu, đông.',
      },
      {
        id: 'g5-tv-w05-q5',
        subject: 'Tiếng Việt',
        content: 'Từ nào thường dùng để tả màu của biển?',
        options: ['xanh biếc', 'đỏ rực', 'vàng óng', 'trắng tinh'],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: '"xanh biếc", "xanh thẳm", "xanh lam" đều tả màu nước biển.',
      },
    ],
  },
  {
    subject: 'Tiếng Việt',
    weekNumber: 6,
    unit: VIET_UNIT_2,
    title: 'Đại từ xưng hô',
    difficulty: 3,
    questions: [
      {
        id: 'g5-tv-w06-q1',
        subject: 'Tiếng Việt',
        content: 'Đại từ xưng hô là từ dùng để làm gì?',
        options: [
          'Tự chỉ mình hoặc chỉ người khác khi nói, khi viết',
          'Chỉ hoạt động của người',
          'Chỉ đặc điểm của sự vật',
          'Nối các câu trong đoạn văn',
        ],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: 'Ví dụ: tôi, tớ, chúng tôi, bạn, các bạn, nó, họ.',
      },
      {
        id: 'g5-tv-w06-q2',
        subject: 'Tiếng Việt',
        content: 'Từ nào là đại từ xưng hô?',
        options: ['tôi', 'bàn', 'chạy', 'đẹp'],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: '"tôi" dùng để người nói tự chỉ mình.',
      },
      {
        id: 'g5-tv-w06-q3',
        subject: 'Tiếng Việt',
        content: 'Trong câu "Chúng tôi đi học sớm.", đại từ xưng hô là từ nào?',
        options: ['chúng tôi', 'đi học', 'sớm', 'học'],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: '"chúng tôi" chỉ người nói cùng những người khác.',
      },
      {
        id: 'g5-tv-w06-q4',
        subject: 'Tiếng Việt',
        content: 'Khi nói với người lớn tuổi, em nên dùng đại từ nào để xưng?',
        options: ['cháu, con', 'tao', 'nó', 'tớ'],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: 'Tiếng Việt chọn đại từ theo quan hệ và thái độ; với người lớn phải xưng lễ phép.',
      },
      {
        id: 'g5-tv-w06-q5',
        subject: 'Tiếng Việt',
        content: 'Đại từ "nó" thường dùng để chỉ ai?',
        options: [
          'Người hoặc vật ở ngôi thứ ba',
          'Chính người đang nói',
          'Người đang nghe',
          'Một nhóm người cùng nói',
        ],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: 'Ngôi thứ ba là người/vật được nói tới, không phải người nói hay người nghe.',
      },
    ],
  },
];
