import type { WeekTopicSeed } from '../types';

/**
 * Lộ trình Lớp 4 — Toán và Tiếng Việt, tuần 1-6 (bộ Kết nối tri thức).
 *
 * 5 câu mỗi tuần, `difficulty: 2` nên hoàn thành một tuần được 4 phút thưởng
 * (Lớp 1-2 chỉ 2 phút) — bài dài hơn và đòi tính toán nhiều bước hơn.
 *
 * Số lớn được viết có **khoảng trắng nhóm ba chữ số** (45 072 chứ không phải
 * 45.072 hay 45,072): đó là cách sách Toán Lớp 4 viết, và cũng tránh lẫn dấu
 * phẩy thập phân mà các em sẽ học ở Lớp 5.
 *
 * Ghi chú về đáp án: đáp án đúng luôn ở vị trí đầu trong tệp dữ liệu;
 * `shuffleQuestionOptions` trộn lại thứ tự mỗi lần tạo đề.
 */

const MATH_UNIT_1 = 'Số tự nhiên đến lớp triệu';
const MATH_UNIT_2 = 'Đơn vị đo, trung bình cộng & phép cộng, trừ';

export const GRADE4_MATH_WEEKS: WeekTopicSeed[] = [
  {
    subject: 'Toán',
    weekNumber: 1,
    unit: MATH_UNIT_1,
    title: 'Các số đến 100 000',
    difficulty: 2,
    questions: [
      {
        id: 'g4-toan-w01-q1',
        subject: 'Toán',
        content: 'Số 45 072 đọc như thế nào?',
        options: [
          'Bốn mươi lăm nghìn không trăm bảy mươi hai',
          'Bốn mươi lăm nghìn bảy mươi hai nghìn',
          'Bốn nghìn năm trăm bảy mươi hai',
          'Bốn mươi lăm nghìn bảy trăm hai',
        ],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Tách thành 45 nghìn và 072: hàng trăm là 0 nên đọc "không trăm bảy mươi hai".',
      },
      {
        id: 'g4-toan-w01-q2',
        subject: 'Toán',
        content: 'Số lớn nhất có năm chữ số là số nào?',
        options: ['99 999', '100 000', '90 000', '99 990'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: '100 000 đã có sáu chữ số, nên số năm chữ số lớn nhất là 99 999.',
      },
      {
        id: 'g4-toan-w01-q3',
        subject: 'Toán',
        content: '60 000 + 3 000 + 500 + 8 = ?',
        options: ['63 508', '63 058', '60 358', '63 580'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: '6 chục nghìn, 3 nghìn, 5 trăm, 0 chục, 8 đơn vị → 63 508.',
      },
      {
        id: 'g4-toan-w01-q4',
        subject: 'Toán',
        content: 'Số liền sau của 89 999 là số nào?',
        options: ['90 000', '89 998', '90 999', '80 000'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Thêm 1 đơn vị: 89 999 + 1 = 90 000.',
      },
      {
        id: 'g4-toan-w01-q5',
        subject: 'Toán',
        content: 'So sánh 47 350 và 47 305.',
        options: [
          '47 350 > 47 305',
          '47 350 < 47 305',
          '47 350 = 47 305',
          'Không so sánh được',
        ],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Ba chữ số đầu giống nhau; tới hàng chục thì 5 > 0 nên 47 350 lớn hơn.',
      },
    ],
  },
  {
    subject: 'Toán',
    weekNumber: 2,
    unit: MATH_UNIT_1,
    title: 'Hàng và lớp',
    difficulty: 2,
    questions: [
      {
        id: 'g4-toan-w02-q1',
        subject: 'Toán',
        content: 'Trong số 82 476, chữ số 4 thuộc hàng nào?',
        options: ['Hàng trăm', 'Hàng chục', 'Hàng nghìn', 'Hàng chục nghìn'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Đếm từ phải sang: 6 đơn vị, 7 chục, 4 trăm.',
      },
      {
        id: 'g4-toan-w02-q2',
        subject: 'Toán',
        content: 'Lớp nghìn gồm những hàng nào?',
        options: [
          'Nghìn, chục nghìn, trăm nghìn',
          'Đơn vị, chục, trăm',
          'Nghìn, triệu, tỉ',
          'Trăm, nghìn, triệu',
        ],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Mỗi lớp gồm ba hàng liền nhau; lớp nghìn là nghìn - chục nghìn - trăm nghìn.',
      },
      {
        id: 'g4-toan-w02-q3',
        subject: 'Toán',
        content: 'Trong số 305 219, chữ số 3 chỉ bao nhiêu?',
        options: ['3 trăm nghìn', '3 nghìn', '3 chục nghìn', '3 trăm'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Số có sáu chữ số nên chữ số đầu tiên thuộc hàng trăm nghìn.',
      },
      {
        id: 'g4-toan-w02-q4',
        subject: 'Toán',
        content: 'Giá trị của chữ số 7 trong số 27 480 là bao nhiêu?',
        options: ['7 000', '700', '70', '7'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Chữ số 7 đứng ở hàng nghìn nên giá trị của nó là 7 000.',
      },
      {
        id: 'g4-toan-w02-q5',
        subject: 'Toán',
        content: 'Lớp đơn vị gồm những hàng nào?',
        options: [
          'Đơn vị, chục, trăm',
          'Đơn vị, chục, nghìn',
          'Chỉ hàng đơn vị',
          'Đơn vị, trăm, nghìn',
        ],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Ba hàng đầu tiên tính từ phải sang tạo thành lớp đơn vị.',
      },
    ],
  },
  {
    subject: 'Toán',
    weekNumber: 3,
    unit: MATH_UNIT_1,
    title: 'Triệu và lớp triệu',
    difficulty: 2,
    questions: [
      {
        id: 'g4-toan-w03-q1',
        subject: 'Toán',
        content: 'Số 1 triệu có mấy chữ số 0?',
        options: ['6', '5', '7', '3'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: '1 triệu viết là 1 000 000 — sau chữ số 1 có 6 chữ số 0.',
      },
      {
        id: 'g4-toan-w03-q2',
        subject: 'Toán',
        content: 'Lớp triệu gồm những hàng nào?',
        options: [
          'Triệu, chục triệu, trăm triệu',
          'Nghìn, chục nghìn, trăm nghìn',
          'Triệu, tỉ, nghìn tỉ',
          'Trăm nghìn, triệu, chục triệu',
        ],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Cùng quy tắc ba hàng một lớp: triệu - chục triệu - trăm triệu.',
      },
      {
        id: 'g4-toan-w03-q3',
        subject: 'Toán',
        content: 'Số 25 000 000 đọc như thế nào?',
        options: [
          'Hai mươi lăm triệu',
          'Hai mươi lăm nghìn',
          'Hai trăm năm mươi triệu',
          'Hai triệu năm trăm nghìn',
        ],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Nhóm ba chữ số cuối và nhóm giữa đều là 000 nên chỉ đọc phần triệu.',
      },
      {
        id: 'g4-toan-w03-q4',
        subject: 'Toán',
        content: 'Mười triệu được viết là số nào?',
        options: ['10 000 000', '1 000 000', '100 000 000', '10 000'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: '1 triệu là 1 000 000; mười triệu thì thêm một chữ số 0 nữa.',
      },
      {
        id: 'g4-toan-w03-q5',
        subject: 'Toán',
        content: 'Trong số 123 456 789, chữ số 3 thuộc hàng nào?',
        options: ['Hàng triệu', 'Hàng nghìn', 'Hàng chục triệu', 'Hàng trăm nghìn'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Nhóm 123 là phần triệu; trong nhóm đó chữ số 3 đứng cuối nên thuộc hàng triệu.',
      },
    ],
  },
  {
    subject: 'Toán',
    weekNumber: 4,
    unit: MATH_UNIT_2,
    title: 'Yến, tạ, tấn',
    difficulty: 2,
    questions: [
      {
        id: 'g4-toan-w04-q1',
        subject: 'Toán',
        content: '1 yến bằng bao nhiêu ki-lô-gam?',
        options: ['10 kg', '100 kg', '1 000 kg', '5 kg'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: '1 yến = 10 kg.',
      },
      {
        id: 'g4-toan-w04-q2',
        subject: 'Toán',
        content: '1 tạ bằng bao nhiêu ki-lô-gam?',
        options: ['100 kg', '10 kg', '1 000 kg', '50 kg'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: '1 tạ = 10 yến = 100 kg.',
      },
      {
        id: 'g4-toan-w04-q3',
        subject: 'Toán',
        content: '1 tấn bằng bao nhiêu ki-lô-gam?',
        options: ['1 000 kg', '100 kg', '10 kg', '10 000 kg'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: '1 tấn = 10 tạ = 1 000 kg.',
      },
      {
        id: 'g4-toan-w04-q4',
        subject: 'Toán',
        content: '3 tấn 5 tạ bằng bao nhiêu ki-lô-gam?',
        options: ['3 500 kg', '3 050 kg', '350 kg', '8 000 kg'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: '3 tấn = 3 000 kg, 5 tạ = 500 kg; cộng lại được 3 500 kg.',
      },
      {
        id: 'g4-toan-w04-q5',
        subject: 'Toán',
        content: '2 yến 6 kg bằng bao nhiêu ki-lô-gam?',
        options: ['26 kg', '206 kg', '16 kg', '62 kg'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: '2 yến = 20 kg, thêm 6 kg nữa được 26 kg.',
      },
    ],
  },
  {
    subject: 'Toán',
    weekNumber: 5,
    unit: MATH_UNIT_2,
    title: 'Giây, thế kỉ và trung bình cộng',
    difficulty: 2,
    questions: [
      {
        id: 'g4-toan-w05-q1',
        subject: 'Toán',
        content: '1 phút bằng bao nhiêu giây?',
        options: ['60 giây', '100 giây', '30 giây', '600 giây'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: '1 phút = 60 giây.',
      },
      {
        id: 'g4-toan-w05-q2',
        subject: 'Toán',
        content: '1 thế kỉ bằng bao nhiêu năm?',
        options: ['100 năm', '10 năm', '1 000 năm', '50 năm'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: '1 thế kỉ = 100 năm.',
      },
      {
        id: 'g4-toan-w05-q3',
        subject: 'Toán',
        content: 'Năm 1945 thuộc thế kỉ nào?',
        options: ['Thế kỉ XX', 'Thế kỉ XIX', 'Thế kỉ XXI', 'Thế kỉ XVIII'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Thế kỉ XX gồm các năm từ 1901 đến 2000, nên 1945 nằm trong đó.',
      },
      {
        id: 'g4-toan-w05-q4',
        subject: 'Toán',
        content: 'Trung bình cộng của 12 và 18 là bao nhiêu?',
        options: ['15', '30', '6', '16'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: '(12 + 18) : 2 = 30 : 2 = 15.',
      },
      {
        id: 'g4-toan-w05-q5',
        subject: 'Toán',
        content: 'Trung bình cộng của 4, 8 và 9 là bao nhiêu?',
        options: ['7', '21', '6', '8'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: '(4 + 8 + 9) : 3 = 21 : 3 = 7.',
      },
    ],
  },
  {
    subject: 'Toán',
    weekNumber: 6,
    unit: MATH_UNIT_2,
    title: 'Cộng, trừ số có nhiều chữ số',
    difficulty: 2,
    questions: [
      {
        id: 'g4-toan-w06-q1',
        subject: 'Toán',
        content: '45 732 + 23 156 = ?',
        options: ['68 888', '68 878', '69 888', '68 988'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Cộng từ hàng đơn vị: 2+6=8, 3+5=8, 7+1=8, 5+3=8, 4+2=6 → 68 888.',
      },
      {
        id: 'g4-toan-w06-q2',
        subject: 'Toán',
        content: '78 500 - 26 341 = ?',
        options: ['52 159', '52 259', '51 159', '52 169'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Đặt tính rồi trừ có nhớ từ phải sang: kết quả 52 159.',
      },
      {
        id: 'g4-toan-w06-q3',
        subject: 'Toán',
        content: 'Tìm x, biết x + 1 250 = 4 000.',
        options: ['x = 2 750', 'x = 5 250', 'x = 2 850', 'x = 3 750'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Muốn tìm số hạng chưa biết thì lấy tổng trừ số hạng đã biết: 4 000 - 1 250 = 2 750.',
      },
      {
        id: 'g4-toan-w06-q4',
        subject: 'Toán',
        content: '123 456 + 78 544 = ?',
        options: ['202 000', '201 000', '202 100', '200 000'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: '456 + 544 = 1 000, nên tổng là 123 000 + 78 000 + 1 000 = 202 000.',
      },
      {
        id: 'g4-toan-w06-q5',
        subject: 'Toán',
        content:
          'Vụ mùa một xã thu được 32 450 kg thóc. Vụ xuân thu nhiều hơn vụ mùa 5 600 kg. Vụ xuân thu được bao nhiêu ki-lô-gam thóc?',
        options: ['38 050 kg', '26 850 kg', '37 050 kg', '38 150 kg'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: '"Nhiều hơn" thì cộng: 32 450 + 5 600 = 38 050 kg.',
      },
    ],
  },
];

const VIET_UNIT_1 = 'Danh từ, động từ, tính từ';
const VIET_UNIT_2 = 'Đoạn văn cảm nghĩ, từ ngữ về phẩm chất & viết hoa';

export const GRADE4_VIETNAMESE_WEEKS: WeekTopicSeed[] = [
  {
    subject: 'Tiếng Việt',
    weekNumber: 1,
    unit: VIET_UNIT_1,
    title: 'Danh từ riêng',
    difficulty: 2,
    questions: [
      {
        id: 'g4-tv-w01-q1',
        subject: 'Tiếng Việt',
        content: 'Từ nào là danh từ riêng?',
        options: ['Hà Nội', 'thành phố', 'dòng sông', 'ngọn núi'],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: '"Hà Nội" là tên riêng của một thành phố cụ thể.',
      },
      {
        id: 'g4-tv-w01-q2',
        subject: 'Tiếng Việt',
        content: 'Danh từ riêng phải viết như thế nào?',
        options: [
          'Viết hoa chữ đầu mỗi tiếng',
          'Viết thường tất cả',
          'Viết hoa toàn bộ chữ',
          'Chỉ viết hoa tiếng cuối',
        ],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Chính tả',
        explanation: 'Ví dụ: Nguyễn Trãi, Hà Nội, Cửu Long.',
      },
      {
        id: 'g4-tv-w01-q3',
        subject: 'Tiếng Việt',
        content: 'Trong câu "Em học ở trường Kim Đồng.", danh từ riêng là từ nào?',
        options: ['Kim Đồng', 'trường', 'em', 'trường Kim Đồng'],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: '"trường" là danh từ chung, chỉ tên riêng "Kim Đồng" mới là danh từ riêng.',
      },
      {
        id: 'g4-tv-w01-q4',
        subject: 'Tiếng Việt',
        content: 'Từ nào KHÔNG phải danh từ riêng?',
        options: ['học sinh', 'Lan', 'Việt Nam', 'Cửu Long'],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: '"học sinh" gọi chung cả một lớp người nên là danh từ chung.',
      },
      {
        id: 'g4-tv-w01-q5',
        subject: 'Tiếng Việt',
        content: 'Tên người "nguyễn văn an" viết đúng chính tả là gì?',
        options: ['Nguyễn Văn An', 'Nguyễn văn an', 'nguyễn Văn An', 'NGUYỄN văn An'],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Chính tả',
        explanation: 'Tên người là danh từ riêng: viết hoa chữ đầu của cả ba tiếng.',
      },
    ],
  },
  {
    subject: 'Tiếng Việt',
    weekNumber: 2,
    unit: VIET_UNIT_1,
    title: 'Danh từ chung và danh từ riêng',
    difficulty: 2,
    questions: [
      {
        id: 'g4-tv-w02-q1',
        subject: 'Tiếng Việt',
        content: 'Danh từ chung là gì?',
        options: [
          'Tên gọi chung của một loại sự vật',
          'Tên riêng của một sự vật cụ thể',
          'Từ chỉ hoạt động',
          'Từ chỉ đặc điểm',
        ],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: 'Ví dụ "sông" gọi chung mọi dòng sông, còn "sông Hồng" là một dòng cụ thể.',
      },
      {
        id: 'g4-tv-w02-q2',
        subject: 'Tiếng Việt',
        content: 'Trong "sông Hồng", đâu là danh từ chung?',
        options: ['sông', 'Hồng', 'sông Hồng', 'Không có'],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: '"sông" là danh từ chung, "Hồng" là danh từ riêng nên viết hoa.',
      },
      {
        id: 'g4-tv-w02-q3',
        subject: 'Tiếng Việt',
        content: 'Cặp nào gồm một danh từ chung và một danh từ riêng?',
        options: ['núi / Ba Vì', 'núi / đồi', 'Ba Vì / Hà Nội', 'cao / thấp'],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: '"núi" gọi chung, "Ba Vì" là tên riêng của một ngọn núi.',
      },
      {
        id: 'g4-tv-w02-q4',
        subject: 'Tiếng Việt',
        content: 'Từ "vua" là danh từ gì?',
        options: ['Danh từ chung', 'Danh từ riêng', 'Động từ', 'Tính từ'],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: '"vua" gọi chung mọi vị vua nên là danh từ chung; "Quang Trung" mới là riêng.',
      },
      {
        id: 'g4-tv-w02-q5',
        subject: 'Tiếng Việt',
        content: 'Trong câu "Bác Hồ là vị lãnh tụ kính yêu.", danh từ riêng là từ nào?',
        options: ['Bác Hồ', 'lãnh tụ', 'vị lãnh tụ', 'kính yêu'],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: '"Bác Hồ" chỉ một người cụ thể nên là danh từ riêng và được viết hoa.',
      },
    ],
  },
  {
    subject: 'Tiếng Việt',
    weekNumber: 3,
    unit: VIET_UNIT_1,
    title: 'Động từ và tính từ',
    difficulty: 2,
    questions: [
      {
        id: 'g4-tv-w03-q1',
        subject: 'Tiếng Việt',
        content: 'Từ nào là động từ?',
        options: ['chạy', 'xanh', 'cao', 'cái bàn'],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: 'Động từ chỉ hoạt động; "chạy" là việc làm được.',
      },
      {
        id: 'g4-tv-w03-q2',
        subject: 'Tiếng Việt',
        content: 'Từ nào là tính từ?',
        options: ['đỏ tươi', 'viết', 'đọc', 'nhảy'],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: 'Tính từ chỉ đặc điểm; "đỏ tươi" mô tả màu sắc.',
      },
      {
        id: 'g4-tv-w03-q3',
        subject: 'Tiếng Việt',
        content: 'Trong câu "Bé ngoan ngoãn học bài.", tính từ là từ nào?',
        options: ['ngoan ngoãn', 'học', 'bé', 'bài'],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: '"ngoan ngoãn" nêu tính nết của bé; "học" là động từ.',
      },
      {
        id: 'g4-tv-w03-q4',
        subject: 'Tiếng Việt',
        content: 'Động từ chỉ điều gì?',
        options: [
          'Hoạt động, trạng thái của sự vật',
          'Đặc điểm, tính chất của sự vật',
          'Tên gọi của sự vật',
          'Số lượng của sự vật',
        ],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: 'Ví dụ hoạt động: chạy, đọc; trạng thái: ngủ, buồn ngủ.',
      },
      {
        id: 'g4-tv-w03-q5',
        subject: 'Tiếng Việt',
        content: 'Câu "Dòng sông xanh biếc." có tính từ nào?',
        options: ['xanh biếc', 'dòng sông', 'sông', 'dòng'],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: '"xanh biếc" tả màu nước sông.',
      },
    ],
  },
  {
    subject: 'Tiếng Việt',
    weekNumber: 4,
    unit: VIET_UNIT_2,
    title: 'Viết đoạn văn nêu cảm nghĩ',
    difficulty: 2,
    questions: [
      {
        id: 'g4-tv-w04-q1',
        subject: 'Tiếng Việt',
        content: 'Đoạn văn nêu cảm nghĩ thường gồm mấy phần?',
        options: [
          '3 phần: mở đầu, triển khai, kết thúc',
          '2 phần: mở đầu và kết thúc',
          '1 phần duy nhất',
          '4 phần',
        ],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện viết',
        explanation: 'Mở đầu giới thiệu, triển khai nêu cảm nghĩ cụ thể, kết thúc khẳng định lại.',
      },
      {
        id: 'g4-tv-w04-q2',
        subject: 'Tiếng Việt',
        content: 'Câu mở đầu đoạn văn nêu cảm nghĩ nên làm gì?',
        options: [
          'Giới thiệu sự việc hoặc nhân vật gợi cảm nghĩ',
          'Kể lại toàn bộ câu chuyện',
          'Nêu ngay bài học rút ra',
          'Miêu tả thật chi tiết cảnh vật',
        ],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện viết',
        explanation: 'Người đọc cần biết em đang nói về cái gì trước khi nghe cảm nghĩ.',
      },
      {
        id: 'g4-tv-w04-q3',
        subject: 'Tiếng Việt',
        content: 'Vì sao bạn nhỏ thấy thương cây bàng?',
        passage:
          'Sân trường em có một cây bàng già. Mùa đông, bàng trút hết lá, thân cây khẳng khiu đứng chịu gió. Em thấy thương cây bàng lắm.',
        options: [
          'Vì mùa đông cây trút hết lá, đứng khẳng khiu chịu gió',
          'Vì cây bàng bị bạn bè trèo lên',
          'Vì cây bàng không có hoa',
          'Vì cây bàng sắp bị chặt',
        ],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Tập đọc',
        explanation: 'Câu thứ hai tả cảnh cây rụng lá và chịu gió, đó là lí do gợi lên cảm nghĩ.',
      },
      {
        id: 'g4-tv-w04-q4',
        subject: 'Tiếng Việt',
        content: 'Cụm từ nào thường dùng để nêu cảm nghĩ?',
        options: ['Em cảm thấy...', 'Em đi...', 'Em ăn...', 'Em ngủ...'],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện viết',
        explanation: '"Em cảm thấy", "Em rất thích", "Em xúc động" đều dẫn vào cảm nghĩ.',
      },
      {
        id: 'g4-tv-w04-q5',
        subject: 'Tiếng Việt',
        content: 'Phần kết thúc đoạn văn nêu cảm nghĩ nên làm gì?',
        options: [
          'Khẳng định lại tình cảm của mình',
          'Mở ra một câu chuyện mới',
          'Đặt một câu hỏi cho người đọc',
          'Nhắc lại nguyên văn phần mở đầu',
        ],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện viết',
        explanation: 'Kết đoạn nên chốt lại tình cảm để đoạn văn trọn ý.',
      },
    ],
  },
  {
    subject: 'Tiếng Việt',
    weekNumber: 5,
    unit: VIET_UNIT_2,
    title: 'Từ ngữ về Trung thực - Tự trọng',
    difficulty: 2,
    questions: [
      {
        id: 'g4-tv-w05-q1',
        subject: 'Tiếng Việt',
        content: 'Từ nào cùng nghĩa với "trung thực"?',
        options: ['thật thà', 'dối trá', 'gian lận', 'lười nhác'],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: '"thật thà", "ngay thẳng", "thành thật" đều gần nghĩa với trung thực.',
      },
      {
        id: 'g4-tv-w05-q2',
        subject: 'Tiếng Việt',
        content: 'Từ nào trái nghĩa với "trung thực"?',
        options: ['dối trá', 'thành thật', 'ngay thẳng', 'chân thật'],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: 'Ba từ còn lại đều cùng nghĩa với trung thực.',
      },
      {
        id: 'g4-tv-w05-q3',
        subject: 'Tiếng Việt',
        content: '"Tự trọng" nghĩa là gì?',
        options: [
          'Coi trọng và giữ gìn phẩm giá của mình',
          'Chỉ nghĩ đến bản thân',
          'Luôn cho mình là giỏi nhất',
          'Không dám nhận lỗi',
        ],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: 'Người tự trọng không làm điều xấu dù không ai nhìn thấy.',
      },
      {
        id: 'g4-tv-w05-q4',
        subject: 'Tiếng Việt',
        content: 'Thành ngữ nào nói về tính trung thực?',
        options: [
          'Thẳng như ruột ngựa',
          'Nước đổ lá khoai',
          'Chậm như rùa',
          'Đứng núi này trông núi nọ',
        ],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: '"Thẳng như ruột ngựa" tả người nói thẳng, thật lòng.',
      },
      {
        id: 'g4-tv-w05-q5',
        subject: 'Tiếng Việt',
        content: 'Hành động nào thể hiện tính trung thực?',
        options: [
          'Nhận lỗi khi mình làm sai',
          'Nhìn bài của bạn khi kiểm tra',
          'Nói dối để khỏi bị mắng',
          'Nhận phần thưởng của người khác',
        ],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Luyện từ và câu',
        explanation: 'Dám nhận lỗi là biểu hiện rõ nhất của trung thực.',
      },
    ],
  },
  {
    subject: 'Tiếng Việt',
    weekNumber: 6,
    unit: VIET_UNIT_2,
    title: 'Viết hoa tên địa lí',
    difficulty: 2,
    questions: [
      {
        id: 'g4-tv-w06-q1',
        subject: 'Tiếng Việt',
        content: 'Tên địa lí Việt Nam được viết như thế nào?',
        options: [
          'Viết hoa chữ đầu mỗi tiếng, ví dụ Hà Nội',
          'Viết thường tất cả, ví dụ hà nội',
          'Viết hoa toàn bộ, ví dụ HÀ NỘI',
          'Chỉ viết hoa tiếng đầu, ví dụ Hà nội',
        ],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Chính tả',
        explanation: 'Tên địa lí là danh từ riêng nên mỗi tiếng đều viết hoa chữ đầu.',
      },
      {
        id: 'g4-tv-w06-q2',
        subject: 'Tiếng Việt',
        content: 'Tên nào viết đúng chính tả?',
        options: ['Thừa Thiên Huế', 'thừa thiên huế', 'Thừa thiên huế', 'THừa Thiên Huế'],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Chính tả',
        explanation: 'Cả ba tiếng đều là bộ phận của tên riêng nên đều viết hoa chữ đầu.',
      },
      {
        id: 'g4-tv-w06-q3',
        subject: 'Tiếng Việt',
        content: 'Tên địa lí nước ngoài phiên âm Hán Việt được viết thế nào?',
        options: [
          'Viết hoa chữ đầu mỗi tiếng, ví dụ Bắc Kinh',
          'Viết thường hết vì là tiếng nước ngoài',
          'Viết hoa toàn bộ chữ',
          'Đặt trong ngoặc kép',
        ],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Chính tả',
        explanation: 'Đã phiên âm Hán Việt thì viết như tên địa lí Việt Nam: Bắc Kinh, Nhật Bản.',
      },
      {
        id: 'g4-tv-w06-q4',
        subject: 'Tiếng Việt',
        content: 'Trong "sông Cửu Long", bộ phận nào phải viết hoa?',
        options: ['Cửu Long', 'sông', 'sông Cửu Long', 'Không phần nào'],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Chính tả',
        explanation: '"sông" là danh từ chung nên viết thường; "Cửu Long" là tên riêng.',
      },
      {
        id: 'g4-tv-w06-q5',
        subject: 'Tiếng Việt',
        content: 'Cách viết nào SAI?',
        options: ['núi Ba vì', 'núi Ba Vì', 'thành phố Hải Phòng', 'tỉnh Nghệ An'],
        correctAnswer: 0,
        rewardMinutes: 3,
        skill: 'Chính tả',
        explanation: 'Tiếng "vì" cũng thuộc tên riêng nên phải viết hoa: núi Ba Vì.',
      },
    ],
  },
];
