import type { Question, WeekTopic } from '../types';

/**
 * Lộ trình Tiếng Việt Lớp 3 theo 35 tuần học.
 *
 * Ba dạng bài, đánh dấu bằng trường `skill` để hiển thị cho học sinh:
 *  - "Tập đọc"          — có `passage`, đọc đoạn văn rồi trả lời
 *  - "Luyện từ và câu"  — từ loại, so sánh, nhân hoá, kiểu câu, dấu câu
 *  - "Chính tả"         — phân biệt l/n, ch/tr, s/x, d/gi/r, dấu hỏi/ngã...
 *
 * Tuần 1-10 soạn chi tiết 5 câu/tuần; tuần 11-35 có đủ tên bài và 3 câu/tuần
 * làm khung để mở rộng.
 *
 * LƯU Ý: không đổi `id` của câu đã có (`tv-01`..`tv-20` từ bản trước, được xếp
 * vào tuần phù hợp) vì `masteredQuestionIds` đã lưu tham chiếu tới các id này.
 */

export const VIETNAMESE_TOTAL_WEEKS = 35;

const UNIT_1 = 'Mái trường em yêu';
const UNIT_2 = 'Cộng đồng & Trái tim yêu thương';
const UNIT_3 = 'Quê hương đất nước';
const UNIT_4 = 'Nghệ thuật & Sáng tạo';
const UNIT_5 = 'Trái Đất màu xanh & Ôn tập cuối năm';

export const VIETNAMESE_WEEKS: WeekTopic[] = [
  /* ============ TUẦN 1-4: MÁI TRƯỜNG EM YÊU ============ */
  {
    subject: 'Tiếng Việt',
    weekNumber: 1,
    unit: UNIT_1,
    title: 'Từ chỉ sự vật ở trường lớp',
    difficulty: 1,
    questions: [
      {
        id: 'tv-06',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Từ nào dưới đây là từ chỉ sự vật?',
        options: ['viết bài', 'xanh tươi', 'chạy nhanh', 'quyển vở'],
        correctAnswer: 3,
        rewardMinutes: 2,
        explanation: '"quyển vở" là đồ vật nên là từ chỉ sự vật.',
      },
      {
        id: 'tv-19',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Từ nào KHÔNG cùng nhóm với các từ còn lại?',
        options: ['bàn', 'ghế', 'chạy', 'tủ'],
        correctAnswer: 2,
        rewardMinutes: 2,
        explanation:
          '"bàn", "ghế", "tủ" đều chỉ đồ vật; còn "chạy" chỉ hoạt động nên khác nhóm.',
      },
      {
        id: 'tv-w01-q1',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Nhóm từ nào dưới đây đều là đồ dùng học tập?',
        options: [
          'bút chì, thước kẻ, cục tẩy',
          'bút chì, con mèo, cái ghế',
          'bảng đen, cây bàng, đám mây',
          'sách vở, chạy nhảy, vui vẻ',
        ],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Bút chì, thước kẻ, cục tẩy đều là đồ dùng học tập của học sinh.',
      },
      {
        id: 'tv-w01-q2',
        subject: 'Tiếng Việt',
        skill: 'Tập đọc',
        passage:
          'Sáng nay, sân trường thật đông vui. Các bạn học sinh mặc áo trắng, quàng khăn đỏ. Dưới gốc bàng, cô giáo đang dặn dò các bạn lớp 3A chuẩn bị vào lớp.',
        content: 'Theo đoạn văn, cô giáo đang đứng ở đâu?',
        options: ['Trong lớp học', 'Dưới gốc bàng', 'Ở cổng trường', 'Trên bục giảng'],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation: 'Đoạn văn viết: "Dưới gốc bàng, cô giáo đang dặn dò các bạn lớp 3A".',
      },
      {
        id: 'tv-w01-q3',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Từ nào dưới đây chỉ người làm việc trong trường học?',
        options: ['bác sĩ', 'thầy giáo', 'công nhân', 'nông dân'],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation: 'Thầy giáo, cô giáo là người dạy học trong trường.',
      },
      {
        id: 'tv-w01-q4',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Từ nào dưới đây là từ chỉ sự vật?',
        options: ['chăm chỉ', 'cặp sách', 'vui vẻ', 'nhảy dây'],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation: '"cặp sách" là đồ vật nên là từ chỉ sự vật.',
      },
      {
        id: 'tv-w01-q5',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Từ nào dưới đây KHÔNG phải từ chỉ sự vật?',
        options: ['bảng đen', 'phấn trắng', 'lau bảng', 'cô giáo'],
        correctAnswer: 2,
        rewardMinutes: 2,
        explanation: '"lau bảng" chỉ hoạt động, ba từ còn lại chỉ sự vật.',
      },
      {
        id: 'tv-w01-q6',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Nhóm từ nào dưới đây đều chỉ người?',
        options: ['học sinh, cô giáo, bác bảo vệ', 'bàn, ghế, bảng', 'chạy, nhảy, hát', 'xanh, đỏ, tím'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Ba từ đầu đều chỉ người trong trường học.',
      },
      {
        id: 'tv-w01-q7',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Nhóm từ nào dưới đây đều chỉ con vật?',
        options: ['gà, vịt, chó', 'cây, hoa, lá', 'bút, vở, thước', 'sáng, trưa, chiều'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Gà, vịt, chó đều là con vật.',
      },
      {
        id: 'tv-w01-q8',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Nhóm từ nào dưới đây đều chỉ cây cối?',
        options: ['bàng, phượng, xoài', 'mèo, cá, chim', 'thầy giáo, bạn bè', 'đọc, viết, vẽ'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Bàng, phượng, xoài đều là tên cây.',
      },
      {
        id: 'tv-w01-q9',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Trong câu "Chiếc cặp của em màu xanh.", từ nào chỉ sự vật?',
        options: ['chiếc cặp', 'của', 'màu xanh', 'em'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: '"chiếc cặp" là đồ vật nên là từ chỉ sự vật.',
      },
      {
        id: 'tv-w01-q10',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Từ nào dưới đây chỉ đồ dùng để viết?',
        options: ['quyển vở', 'cái bút', 'cái cặp', 'chiếc ghế'],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation: 'Cái bút là đồ dùng để viết.',
      },
      {
        id: 'tv-w01-q11',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Nhóm từ nào dưới đây đều là đồ vật trong lớp học?',
        options: ['bảng, bàn, ghế', 'sông, núi, biển', 'mưa, nắng, gió', 'chạy, đi, đứng'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Bảng, bàn, ghế đều có trong lớp học.',
      },
      {
        id: 'tv-w01-q12',
        subject: 'Tiếng Việt',
        skill: 'Tập đọc',
        passage:
          'Sáng nay, sân trường thật đông vui. Các bạn học sinh mặc áo trắng, quàng khăn đỏ. Dưới gốc bàng, cô giáo đang dặn dò các bạn lớp 3A chuẩn bị vào lớp.',
        content: 'Theo đoạn văn, các bạn học sinh mặc gì?',
        options: ['Áo trắng, quàng khăn đỏ', 'Áo xanh, đội mũ', 'Áo vàng, đi giày', 'Áo hoa, đeo cặp'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Đoạn văn viết: "Các bạn học sinh mặc áo trắng, quàng khăn đỏ".',
      },
      {
        id: 'tv-w01-q13',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Người dạy học ở trường được gọi là gì?',
        options: ['bác sĩ', 'thầy cô giáo', 'kĩ sư', 'nông dân'],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation: 'Thầy cô giáo là người dạy học.',
      },
      {
        id: 'tv-w01-q14',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Người khám bệnh cho em được gọi là gì?',
        options: ['bác sĩ', 'giáo viên', 'công an', 'đầu bếp'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Bác sĩ là người khám và chữa bệnh.',
      },
      {
        id: 'tv-w01-q15',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Từ nào dưới đây chỉ nơi chốn?',
        options: ['sân trường', 'chạy nhảy', 'sạch sẽ', 'vui vẻ'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '"sân trường" là một địa điểm.',
      },
      {
        id: 'tv-w01-q16',
        subject: 'Tiếng Việt',
        skill: 'Chính tả',
        content: 'Từ nào dưới đây viết ĐÚNG chính tả?',
        options: ['quyển vở', 'quyễn vở', 'quển vở', 'quyển vỡ'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Viết đúng là "quyển vở".',
      },
      {
        id: 'tv-w01-q17',
        subject: 'Tiếng Việt',
        skill: 'Chính tả',
        content: 'Từ nào dưới đây viết ĐÚNG chính tả?',
        options: ['cặp sách', 'cặb sách', 'cặp xách', 'cặb xách'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Viết đúng là "cặp sách".',
      },
      {
        id: 'tv-w01-q18',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Từ nào KHÔNG cùng nhóm với các từ còn lại?',
        options: ['thước kẻ', 'bút chì', 'cục tẩy', 'chạy bộ'],
        correctAnswer: 3,
        rewardMinutes: 2,
        explanation: 'Ba từ đầu là đồ dùng học tập, "chạy bộ" chỉ hoạt động.',
      },
      {
        id: 'tv-w01-q19',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Từ nào KHÔNG cùng nhóm với các từ còn lại?',
        options: ['con mèo', 'con chó', 'con gà', 'cái bàn'],
        correctAnswer: 3,
        rewardMinutes: 2,
        explanation: 'Ba từ đầu chỉ con vật, "cái bàn" chỉ đồ vật.',
      },
      {
        id: 'tv-w01-q20',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Trong câu "Trên sân trường có cây bàng to.", từ nào chỉ cây cối?',
        options: ['sân trường', 'cây bàng', 'to', 'trên'],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation: '"cây bàng" là tên một loại cây.',
      },
      {
        id: 'tv-w01-q21',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Từ "lớp học" thuộc nhóm từ chỉ gì?',
        options: ['Sự vật', 'Hoạt động', 'Đặc điểm', 'Số lượng'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '"lớp học" là một nơi chốn, thuộc nhóm từ chỉ sự vật.',
      },
      {
        id: 'tv-w01-q22',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Nhóm từ nào dưới đây đều chỉ hiện tượng tự nhiên?',
        options: ['mưa, nắng, gió', 'bàn, ghế, tủ', 'đi, chạy, nhảy', 'ngoan, giỏi, chăm'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Mưa, nắng, gió đều là hiện tượng của tự nhiên.',
      },
      {
        id: 'tv-w01-q23',
        subject: 'Tiếng Việt',
        skill: 'Chính tả',
        content: 'Từ nào dưới đây viết ĐÚNG chính tả?',
        options: ['bàn ghế', 'bàng ghế', 'bàn ghé', 'bàng ghé'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Viết đúng là "bàn ghế".',
      },
],
  },
  {
    subject: 'Tiếng Việt',
    weekNumber: 2,
    unit: UNIT_1,
    title: 'Từ chỉ hoạt động và chính tả l/n',
    difficulty: 1,
    questions: [
      {
        id: 'tv-01',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Từ nào dưới đây là từ chỉ hoạt động?',
        options: ['bàn ghế', 'chạy nhảy', 'xinh đẹp', 'con mèo'],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation:
          '"chạy nhảy" chỉ hoạt động. "bàn ghế", "con mèo" chỉ sự vật; "xinh đẹp" chỉ đặc điểm.',
      },
      {
        id: 'tv-09',
        subject: 'Tiếng Việt',
        skill: 'Chính tả',
        content: 'Từ nào dưới đây viết ĐÚNG chính tả?',
        options: ['no lắng', 'lo nắng', 'lo lắng', 'no nắng'],
        correctAnswer: 2,
        rewardMinutes: 2,
        explanation: 'Viết đúng là "lo lắng" — cả hai tiếng đều bắt đầu bằng "l".',
      },
      {
        id: 'tv-w02-q1',
        subject: 'Tiếng Việt',
        skill: 'Chính tả',
        content: 'Điền chữ đúng vào chỗ trống: "Mặt trời toả ...ắng ấm áp."',
        options: ['n', 'l', 'nh', 'ng'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Viết đúng là "nắng" (ánh nắng mặt trời), nên điền chữ "n".',
      },
      {
        id: 'tv-w02-q2',
        subject: 'Tiếng Việt',
        skill: 'Chính tả',
        content: 'Từ nào dưới đây viết ĐÚNG chính tả?',
        options: ['nàm việc', 'làm việc', 'nàm viêc', 'làm viêc'],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation: 'Viết đúng là "làm việc" — bắt đầu bằng "l" và tiếng "việc" có dấu nặng.',
      },
      {
        id: 'tv-w02-q3',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Trong câu "Em quét sân giúp mẹ.", từ nào chỉ hoạt động?',
        options: ['Em', 'quét', 'sân', 'mẹ'],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation: '"quét" là việc em làm nên là từ chỉ hoạt động.',
      },
      {
        id: 'tv-w02-q4',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Từ nào dưới đây là từ chỉ hoạt động?',
        options: ['quyển sách', 'đọc sách', 'sách mới', 'trên bàn'],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation: '"đọc sách" là việc làm nên là từ chỉ hoạt động.',
      },
      {
        id: 'tv-w02-q5',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Từ nào dưới đây KHÔNG phải từ chỉ hoạt động?',
        options: ['nhảy dây', 'tưới cây', 'xinh xắn', 'quét nhà'],
        correctAnswer: 2,
        rewardMinutes: 2,
        explanation: '"xinh xắn" chỉ đặc điểm, ba từ còn lại chỉ hoạt động.',
      },
      {
        id: 'tv-w02-q6',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Nhóm từ nào dưới đây đều chỉ hoạt động?',
        options: ['chạy, nhảy, bơi', 'bàn, ghế, tủ', 'đẹp, ngoan, giỏi', 'sáng, trưa, chiều'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Chạy, nhảy, bơi đều là việc làm.',
      },
      {
        id: 'tv-w02-q7',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Trong câu "Bố em đang đọc báo.", từ nào chỉ hoạt động?',
        options: ['Bố em', 'đang', 'đọc', 'báo'],
        correctAnswer: 2,
        rewardMinutes: 3,
        explanation: '"đọc" là việc bố đang làm.',
      },
      {
        id: 'tv-w02-q8',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Trong câu "Chúng em trồng cây ở sân trường.", từ nào chỉ hoạt động?',
        options: ['Chúng em', 'trồng', 'cây', 'sân trường'],
        correctAnswer: 1,
        rewardMinutes: 3,
        explanation: '"trồng" là việc các bạn đang làm.',
      },
      {
        id: 'tv-w02-q9',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Chọn từ chỉ hoạt động để điền: "Mỗi sáng em ... răng rồi rửa mặt."',
        options: ['sạch', 'đánh', 'trắng', 'bàn'],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation: '"đánh răng" là việc em làm mỗi sáng.',
      },
      {
        id: 'tv-w02-q10',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Chọn từ chỉ hoạt động để điền: "Bà em ... rau ngoài vườn."',
        options: ['xanh', 'tưới', 'to', 'vườn'],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation: '"tưới rau" là việc bà làm.',
      },
      {
        id: 'tv-w02-q11',
        subject: 'Tiếng Việt',
        skill: 'Chính tả',
        content: 'Từ nào dưới đây viết ĐÚNG chính tả?',
        options: ['nàng nghe', 'lắng nghe', 'nắng nghe', 'làng nghe'],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation: 'Viết đúng là "lắng nghe".',
      },
      {
        id: 'tv-w02-q12',
        subject: 'Tiếng Việt',
        skill: 'Chính tả',
        content: 'Từ nào dưới đây viết ĐÚNG chính tả?',
        options: ['no nê', 'lo lê', 'no lê', 'lo nê'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Viết đúng là "no nê" (nghĩa là ăn đã đủ).',
      },
      {
        id: 'tv-w02-q13',
        subject: 'Tiếng Việt',
        skill: 'Chính tả',
        content: 'Từ nào dưới đây viết ĐÚNG chính tả?',
        options: ['nặng nhọc', 'lặng nhọc', 'nặng lhọc', 'lặng lhọc'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Viết đúng là "nặng nhọc".',
      },
      {
        id: 'tv-w02-q14',
        subject: 'Tiếng Việt',
        skill: 'Chính tả',
        content: 'Điền chữ đúng: "Trời hôm nay ...ạnh quá!"',
        options: ['n', 'l', 'nh', 'ng'],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation: 'Viết đúng là "lạnh".',
      },
      {
        id: 'tv-w02-q15',
        subject: 'Tiếng Việt',
        skill: 'Chính tả',
        content: 'Điền chữ đúng: "Quả ...a chín thơm lừng."',
        options: ['l', 'n', 'nh', 'ng'],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation: 'Viết đúng là "quả na", nên điền chữ "n".',
      },
      {
        id: 'tv-w02-q16',
        subject: 'Tiếng Việt',
        skill: 'Chính tả',
        content: 'Từ nào dưới đây viết SAI chính tả?',
        options: ['lá cây', 'nước lã', 'lo ngại', 'nàm bài'],
        correctAnswer: 3,
        rewardMinutes: 3,
        explanation: '"nàm bài" sai, phải viết là "làm bài".',
      },
      {
        id: 'tv-w02-q17',
        subject: 'Tiếng Việt',
        skill: 'Chính tả',
        content: 'Từ nào dưới đây viết ĐÚNG chính tả?',
        options: ['lười nhác', 'nười nhác', 'lười lhác', 'nười lhác'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Viết đúng là "lười nhác".',
      },
      {
        id: 'tv-w02-q18',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Trong câu "Các bạn nhỏ vui vẻ nô đùa.", từ nào chỉ hoạt động?',
        options: ['Các bạn nhỏ', 'vui vẻ', 'nô đùa', 'nhỏ'],
        correctAnswer: 2,
        rewardMinutes: 3,
        explanation: '"nô đùa" là việc các bạn đang làm; "vui vẻ" chỉ đặc điểm.',
      },
      {
        id: 'tv-w02-q19',
        subject: 'Tiếng Việt',
        skill: 'Tập đọc',
        passage:
          'Mẹ đi làm về muộn. Nam ra sân, cầm chiếc chổi quét thật sạch. Khi mẹ về, sân đã gọn gàng, mẹ xoa đầu Nam khen ngoan.',
        content: 'Theo đoạn văn, bạn Nam giúp mẹ việc gì?',
        options: ['Rửa bát', 'Quét sân', 'Tưới cây', 'Nấu cơm'],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation: 'Đoạn văn viết: "Nam ra sân, cầm chiếc chổi quét thật sạch".',
      },
      {
        id: 'tv-w02-q20',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Từ nào dưới đây vừa có thể chỉ sự vật, vừa có thể chỉ hoạt động?',
        options: ['cái bàn', 'cày', 'xinh đẹp', 'rất'],
        correctAnswer: 1,
        rewardMinutes: 3,
        explanation: '"cày" có thể là cái cày (sự vật) hoặc việc cày ruộng (hoạt động).',
      },
      {
        id: 'tv-w02-q21',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Câu nào dưới đây có từ chỉ hoạt động?',
        options: ['Bông hoa rất đẹp.', 'Em tưới hoa mỗi ngày.', 'Hoa màu hồng.', 'Đó là bông hoa hồng.'],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation: '"tưới" là việc em làm.',
      },
      {
        id: 'tv-w02-q22',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Nhóm từ nào dưới đây đều chỉ hoạt động học tập?',
        options: ['đọc, viết, tính toán', 'ăn, ngủ, chơi', 'to, nhỏ, dài', 'bút, vở, bảng'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Đọc, viết, tính toán đều là hoạt động học tập.',
      },
      {
        id: 'tv-w02-q23',
        subject: 'Tiếng Việt',
        skill: 'Chính tả',
        content: 'Từ nào dưới đây viết ĐÚNG chính tả?',
        options: ['lo lắng', 'no náng', 'lo náng', 'no lắng'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Viết đúng là "lo lắng".',
      },
],
  },
  {
    subject: 'Tiếng Việt',
    weekNumber: 3,
    unit: UNIT_1,
    title: 'Câu giới thiệu và câu nêu hoạt động',
    difficulty: 1,
    questions: [
      {
        id: 'tv-07',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Câu "Mẹ em là giáo viên." thuộc mẫu câu nào?',
        options: ['Ai là gì?', 'Ai làm gì?', 'Ai thế nào?', 'Ở đâu?'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Có từ "là" và giới thiệu nghề nghiệp nên thuộc mẫu "Ai là gì?".',
      },
      {
        id: 'tv-03',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Câu "Bạn Lan đang tưới cây." thuộc mẫu câu nào?',
        options: ['Ai là gì?', 'Ai làm gì?', 'Ai thế nào?', 'Ở đâu?'],
        correctAnswer: 1,
        rewardMinutes: 3,
        explanation:
          '"Bạn Lan" trả lời cho câu hỏi "Ai?", "đang tưới cây" trả lời cho "làm gì?".',
      },
      {
        id: 'tv-w03-q1',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Câu nào dưới đây là câu GIỚI THIỆU?',
        options: [
          'Nam đá bóng ngoài sân.',
          'Nam là học sinh lớp 3B.',
          'Nam chạy rất nhanh.',
          'Nam ơi, lại đây!',
        ],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation: 'Câu giới thiệu thường có từ "là" để nói người đó là ai.',
      },
      {
        id: 'tv-w03-q2',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Bộ phận nào trả lời cho câu hỏi "Ai?" trong câu "Bà em kể chuyện cổ tích."?',
        options: ['Bà em', 'kể chuyện', 'chuyện cổ tích', 'cổ tích'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '"Bà em" là người thực hiện hoạt động nên trả lời cho "Ai?".',
      },
      {
        id: 'tv-w03-q3',
        subject: 'Tiếng Việt',
        skill: 'Tập đọc',
        passage:
          'Lớp 3A có một góc thư viện nhỏ. Trên giá sách có truyện tranh, sách khoa học và cả từ điển. Giờ ra chơi, các bạn thường đến đó đọc sách.',
        content: 'Các bạn thường đến góc thư viện vào lúc nào?',
        options: ['Trước giờ vào lớp', 'Giờ ra chơi', 'Sau khi tan học', 'Buổi tối'],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation: 'Đoạn văn viết: "Giờ ra chơi, các bạn thường đến đó đọc sách".',
      },
      {
        id: 'tv-w03-q4',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Câu nào dưới đây là câu NÊU HOẠT ĐỘNG?',
        options: ['Nam là học sinh lớp 3B.', 'Nam đá bóng ngoài sân.', 'Nam rất cao.', 'Nam ơi!'],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation: '"đá bóng" là hoạt động Nam đang làm.',
      },
      {
        id: 'tv-w03-q5',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Câu "Chị em là bác sĩ." thuộc mẫu câu nào?',
        options: ['Ai là gì?', 'Ai làm gì?', 'Ai thế nào?', 'Ở đâu?'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Có từ "là" và giới thiệu nghề nghiệp.',
      },
      {
        id: 'tv-w03-q6',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Câu "Ông em trồng rau trong vườn." thuộc mẫu câu nào?',
        options: ['Ai là gì?', 'Ai làm gì?', 'Ai thế nào?', 'Khi nào?'],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation: '"trồng rau" là hoạt động của ông.',
      },
      {
        id: 'tv-w03-q7',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Bộ phận nào trả lời cho câu hỏi "Làm gì?" trong câu "Các bạn hát rất hay."',
        options: ['Các bạn', 'hát', 'rất hay', 'bạn'],
        correctAnswer: 1,
        rewardMinutes: 3,
        explanation: '"hát" là hoạt động các bạn đang làm.',
      },
      {
        id: 'tv-w03-q8',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Bộ phận nào trả lời cho câu hỏi "Ai?" trong câu "Mẹ nấu cơm."',
        options: ['Mẹ', 'nấu', 'cơm', 'nấu cơm'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '"Mẹ" là người thực hiện hoạt động.',
      },
      {
        id: 'tv-w03-q9',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Từ nào thường xuất hiện trong câu giới thiệu?',
        options: ['là', 'đang', 'rất', 'không'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Câu giới thiệu thường có từ "là".',
      },
      {
        id: 'tv-w03-q10',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Đặt câu giới thiệu về bản thân, câu nào đúng nhất?',
        options: ['Em là học sinh lớp 3.', 'Em chạy rất nhanh.', 'Em ơi, lại đây!', 'Em có đi học không?'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Câu có từ "là" và giới thiệu em là ai.',
      },
      {
        id: 'tv-w03-q11',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Câu nào dưới đây KHÔNG phải câu giới thiệu?',
        options: ['Bố em là công nhân.', 'Đây là quyển vở của em.', 'Em quét lớp mỗi ngày.', 'Hà Nội là thủ đô nước ta.'],
        correctAnswer: 2,
        rewardMinutes: 3,
        explanation: 'Câu đó nêu hoạt động chứ không giới thiệu.',
      },
      {
        id: 'tv-w03-q12',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Điền từ thích hợp: "Bạn Lan ... lớp trưởng của lớp em."',
        options: ['là', 'đang', 'rất', 'ở'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Câu giới thiệu dùng từ "là".',
      },
      {
        id: 'tv-w03-q13',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Điền từ chỉ hoạt động: "Chúng em ... bài trước khi đến lớp."',
        options: ['học', 'giỏi', 'sạch', 'lớp'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '"học bài" là hoạt động.',
      },
      {
        id: 'tv-w03-q14',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Trong câu "Cô giáo giảng bài rất hay.", bộ phận nào trả lời câu hỏi "Ai?"',
        options: ['Cô giáo', 'giảng bài', 'rất hay', 'bài'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '"Cô giáo" là người thực hiện hoạt động.',
      },
      {
        id: 'tv-w03-q15',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Câu nào dưới đây viết đúng và đủ ý?',
        options: ['Em đi học.', 'Đi học em.', 'Học em đi.', 'Em học đi.'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Câu đúng cần có trật tự "Ai làm gì": Em (ai) đi học (làm gì).',
      },
      {
        id: 'tv-w03-q16',
        subject: 'Tiếng Việt',
        skill: 'Chính tả',
        content: 'Từ nào dưới đây viết ĐÚNG chính tả?',
        options: ['lớp trưởng', 'nớp trưởng', 'lớp chưởng', 'nớp chưởng'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Viết đúng là "lớp trưởng".',
      },
      {
        id: 'tv-w03-q17',
        subject: 'Tiếng Việt',
        skill: 'Chính tả',
        content: 'Từ nào dưới đây viết ĐÚNG chính tả?',
        options: ['giảng bài', 'dảng bài', 'rảng bài', 'giãng bài'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Viết đúng là "giảng bài".',
      },
      {
        id: 'tv-w03-q18',
        subject: 'Tiếng Việt',
        skill: 'Tập đọc',
        passage:
          'Lớp 3A có một góc thư viện nhỏ. Trên giá sách có truyện tranh, sách khoa học và cả từ điển. Giờ ra chơi, các bạn thường đến đó đọc sách.',
        content: 'Theo đoạn văn, góc thư viện của lớp có những gì?',
        options: ['Chỉ có truyện tranh', 'Truyện tranh, sách khoa học và từ điển', 'Chỉ có từ điển', 'Bàn ghế và bảng đen'],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation: 'Đoạn văn viết: "Trên giá sách có truyện tranh, sách khoa học và cả từ điển".',
      },
      {
        id: 'tv-w03-q19',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Câu "Hà Nội là thủ đô của nước Việt Nam." thuộc mẫu câu nào?',
        options: ['Ai là gì?', 'Ai làm gì?', 'Ai thế nào?', 'Ở đâu?'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Câu giới thiệu Hà Nội là gì, có từ "là".',
      },
      {
        id: 'tv-w03-q20',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Bộ phận in đậm trả lời câu hỏi gì: "Bạn Minh ĐANG LÀM BÀI TẬP."',
        options: ['Ai?', 'Làm gì?', 'Thế nào?', 'Ở đâu?'],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation: '"đang làm bài tập" nêu hoạt động nên trả lời "Làm gì?".',
      },
      {
        id: 'tv-w03-q21',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Câu nào dưới đây có đủ hai bộ phận "Ai" và "làm gì"?',
        options: ['Rất nhanh.', 'Chim hót.', 'Trên cây.', 'Đẹp quá!'],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation: '"Chim" (ai) và "hót" (làm gì).',
      },
      {
        id: 'tv-w03-q22',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Từ nào dưới đây chỉ hoạt động của học sinh trong lớp?',
        options: ['phát biểu', 'bảng đen', 'sạch sẽ', 'buổi sáng'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '"phát biểu" là việc học sinh làm trong lớp.',
      },
      {
        id: 'tv-w03-q23',
        subject: 'Tiếng Việt',
        skill: 'Chính tả',
        content: 'Từ nào dưới đây viết ĐÚNG chính tả?',
        options: ['chăm ngoan', 'trăm ngoan', 'chăm ngan', 'trăm ngan'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Viết đúng là "chăm ngoan".',
      },
],
  },
  {
    subject: 'Tiếng Việt',
    weekNumber: 4,
    unit: UNIT_1,
    title: 'Từ chỉ đặc điểm và câu "Ai thế nào?"',
    difficulty: 1,
    questions: [
      {
        id: 'tv-05',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Từ nào dưới đây là từ chỉ đặc điểm?',
        options: ['học sinh', 'tròn xoe', 'đọc sách', 'cái bút'],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation:
          '"tròn xoe" chỉ đặc điểm (hình dáng). "học sinh", "cái bút" chỉ sự vật; "đọc sách" chỉ hoạt động.',
      },
      {
        id: 'tv-08',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Câu "Bầu trời rất trong xanh." thuộc mẫu câu nào?',
        options: ['Ai làm gì?', 'Ai là gì?', 'Ai thế nào?', 'Khi nào?'],
        correctAnswer: 2,
        rewardMinutes: 2,
        explanation:
          '"rất trong xanh" nói về đặc điểm của bầu trời nên thuộc mẫu "Ai thế nào?".',
      },
      {
        id: 'tv-w04-q1',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Chọn từ chỉ đặc điểm để điền: "Mái tóc của bà ... như mây."',
        options: ['chạy', 'bạc trắng', 'quyển vở', 'buổi sáng'],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation: '"bạc trắng" tả màu sắc của mái tóc nên là từ chỉ đặc điểm.',
      },
      {
        id: 'tv-w04-q2',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Câu nào dưới đây thuộc mẫu "Ai thế nào?"',
        options: [
          'Em đi học lúc 7 giờ.',
          'Bạn Hoa rất chăm chỉ.',
          'Bố em là bộ đội.',
          'Chúng em quét lớp.',
        ],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation: '"rất chăm chỉ" nêu đặc điểm của bạn Hoa.',
      },
      {
        id: 'tv-w04-q3',
        subject: 'Tiếng Việt',
        skill: 'Chính tả',
        content: 'Từ nào dưới đây viết ĐÚNG chính tả?',
        options: ['lung linh', 'nung ninh', 'lung ninh', 'nung linh'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Viết đúng là "lung linh" — cả hai tiếng đều bắt đầu bằng "l".',
      },
      {
        id: 'tv-w04-q4',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Từ nào dưới đây là từ chỉ đặc điểm?',
        options: ['chạy nhanh', 'cao lớn', 'quét nhà', 'cái bút'],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation: '"cao lớn" nói lên đặc điểm hình dáng.',
      },
      {
        id: 'tv-w04-q5',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Từ nào dưới đây KHÔNG phải từ chỉ đặc điểm?',
        options: ['tròn', 'đỏ', 'ngọt', 'nhảy'],
        correctAnswer: 3,
        rewardMinutes: 2,
        explanation: '"nhảy" chỉ hoạt động, ba từ còn lại chỉ đặc điểm.',
      },
      {
        id: 'tv-w04-q6',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Nhóm từ nào dưới đây đều chỉ màu sắc?',
        options: ['xanh, đỏ, vàng', 'tròn, vuông, dài', 'ngọt, mặn, chua', 'đi, đứng, ngồi'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Xanh, đỏ, vàng đều là màu sắc.',
      },
      {
        id: 'tv-w04-q7',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Nhóm từ nào dưới đây đều chỉ mùi vị?',
        options: ['ngọt, mặn, đắng', 'cao, thấp, béo', 'trắng, đen, nâu', 'chạy, bơi, leo'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Ngọt, mặn, đắng đều là vị.',
      },
      {
        id: 'tv-w04-q8',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Nhóm từ nào dưới đây đều chỉ hình dáng?',
        options: ['tròn, vuông, dài', 'thơm, thối, hắc', 'buồn, vui, giận', 'viết, đọc, vẽ'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Tròn, vuông, dài đều nói về hình dáng.',
      },
      {
        id: 'tv-w04-q9',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Câu "Bạn Lan rất chăm chỉ." thuộc mẫu câu nào?',
        options: ['Ai là gì?', 'Ai làm gì?', 'Ai thế nào?', 'Ở đâu?'],
        correctAnswer: 2,
        rewardMinutes: 3,
        explanation: '"chăm chỉ" nêu đặc điểm nên là mẫu "Ai thế nào?".',
      },
      {
        id: 'tv-w04-q10',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Câu nào dưới đây thuộc mẫu "Ai thế nào?"',
        options: ['Em là học sinh.', 'Em đang học bài.', 'Quả cam rất ngọt.', 'Em ơi, lại đây!'],
        correctAnswer: 2,
        rewardMinutes: 2,
        explanation: '"rất ngọt" nêu đặc điểm của quả cam.',
      },
      {
        id: 'tv-w04-q11',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Trong câu "Con đường làng rất rộng.", từ nào chỉ đặc điểm?',
        options: ['con đường', 'làng', 'rộng', 'rất'],
        correctAnswer: 2,
        rewardMinutes: 3,
        explanation: '"rộng" là đặc điểm của con đường.',
      },
      {
        id: 'tv-w04-q12',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Điền từ chỉ đặc điểm: "Bầu trời hôm nay thật ..."',
        options: ['chạy', 'trong xanh', 'quét', 'quyển vở'],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation: '"trong xanh" là đặc điểm của bầu trời.',
      },
      {
        id: 'tv-w04-q13',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Điền từ chỉ đặc điểm: "Tiếng chim nghe rất ..."',
        options: ['vui tai', 'nấu ăn', 'cái bàn', 'đi bộ'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '"vui tai" nêu đặc điểm của âm thanh.',
      },
      {
        id: 'tv-w04-q14',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Từ trái nghĩa với "cao" là gì?',
        options: ['thấp', 'to', 'dài', 'rộng'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '"cao" trái nghĩa với "thấp".',
      },
      {
        id: 'tv-w04-q15',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Từ trái nghĩa với "sạch" là gì?',
        options: ['bẩn', 'mới', 'đẹp', 'nhanh'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '"sạch" trái nghĩa với "bẩn".',
      },
      {
        id: 'tv-w04-q16',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Từ trái nghĩa với "siêng năng" là gì?',
        options: ['lười biếng', 'chăm chỉ', 'ngoan ngoãn', 'nhanh nhẹn'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: '"siêng năng" trái nghĩa với "lười biếng".',
      },
      {
        id: 'tv-w04-q17',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Từ nào gần nghĩa với "vui vẻ"?',
        options: ['phấn khởi', 'buồn bã', 'lo lắng', 'tức giận'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: '"vui vẻ" và "phấn khởi" đều chỉ tâm trạng tốt.',
      },
      {
        id: 'tv-w04-q18',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Bộ phận nào trả lời câu hỏi "Thế nào?" trong câu "Bông hoa này rất thơm."',
        options: ['Bông hoa này', 'rất thơm', 'hoa', 'này'],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation: '"rất thơm" nêu đặc điểm của bông hoa.',
      },
      {
        id: 'tv-w04-q19',
        subject: 'Tiếng Việt',
        skill: 'Tập đọc',
        passage:
          'Giữa sân trường em có một cây bàng già. Mùa hè, lá bàng xanh mát, tán xoè rộng như cái ô cho chúng em ngồi chơi. Sang đông, lá chuyển màu đỏ rồi rụng dần, chỉ còn những cành khẳng khiu.',
        content: 'Theo đoạn văn, cây bàng vào mùa hè có đặc điểm gì?',
        options: ['Lá đỏ và rụng hết', 'Lá xanh mát, tán rộng', 'Trơ trụi cành', 'Nở hoa màu hồng'],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation: 'Đoạn văn viết: "Mùa hè, lá bàng xanh mát, tán xoè rộng như cái ô".',
      },
      {
        id: 'tv-w04-q20',
        subject: 'Tiếng Việt',
        skill: 'Chính tả',
        content: 'Từ nào dưới đây viết ĐÚNG chính tả?',
        options: ['siêng năng', 'xiêng năng', 'siêng nắng', 'xiêng nắng'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Viết đúng là "siêng năng".',
      },
      {
        id: 'tv-w04-q21',
        subject: 'Tiếng Việt',
        skill: 'Chính tả',
        content: 'Từ nào dưới đây viết ĐÚNG chính tả?',
        options: ['trong xanh', 'chong xanh', 'trong sanh', 'chong sanh'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Viết đúng là "trong xanh".',
      },
      {
        id: 'tv-w04-q22',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Câu nào dưới đây dùng từ chỉ đặc điểm SAI?',
        options: ['Quả ớt rất cay.', 'Đường rất ngọt.', 'Bạn Nam rất chăm chỉ.', 'Cái bàn rất ngọt.'],
        correctAnswer: 3,
        rewardMinutes: 3,
        explanation: 'Cái bàn không có vị nên không thể "ngọt".',
      },
      {
        id: 'tv-w04-q23',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Từ nào chỉ đặc điểm tính cách của người?',
        options: ['thật thà', 'quyển vở', 'chạy bộ', 'buổi chiều'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '"thật thà" là nét tính cách.',
      },
],
  },

  /* ====== TUẦN 5-10: CỘNG ĐỒNG & TRÁI TIM YÊU THƯƠNG ====== */
  {
    subject: 'Tiếng Việt',
    weekNumber: 5,
    unit: UNIT_2,
    title: 'Từ ngữ về gia đình',
    difficulty: 1,
    questions: [
      {
        id: 'tv-w05-q1',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Nhóm từ nào dưới đây đều chỉ người trong gia đình?',
        options: [
          'ông, bà, cha, mẹ',
          'ông, bà, thầy giáo, bác sĩ',
          'cha, mẹ, bàn, ghế',
          'anh, chị, chạy, nhảy',
        ],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Ông, bà, cha, mẹ đều là người thân trong gia đình.',
      },
      {
        id: 'tv-w05-q2',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Em gái của mẹ em thì em gọi là gì?',
        options: ['cô', 'dì', 'bác', 'chú'],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation: 'Em gái của mẹ gọi là dì; em gái của bố gọi là cô.',
      },
      {
        id: 'tv-w05-q3',
        subject: 'Tiếng Việt',
        skill: 'Tập đọc',
        passage:
          'Chiều nào bà cũng ngồi bên hiên têm trầu. Em ngồi cạnh, nghe bà kể chuyện ngày xưa. Giọng bà chậm rãi, ấm áp như nắng cuối chiều.',
        content: 'Giọng của bà được tả như thế nào?',
        options: [
          'To và vang',
          'Chậm rãi, ấm áp',
          'Nhanh và vui',
          'Nhỏ và buồn',
        ],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation: 'Đoạn văn viết: "Giọng bà chậm rãi, ấm áp như nắng cuối chiều".',
      },
      {
        id: 'tv-w05-q4',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Từ nào dưới đây chỉ TÌNH CẢM trong gia đình?',
        options: ['bàn ghế', 'yêu thương', 'quét nhà', 'buổi sáng'],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation: '"yêu thương" nói về tình cảm giữa những người thân.',
      },
      {
        id: 'tv-w05-q5',
        subject: 'Tiếng Việt',
        skill: 'Chính tả',
        content: 'Từ nào dưới đây viết ĐÚNG chính tả?',
        options: ['chăm sóc', 'trăm sóc', 'chăm xóc', 'trăm xóc'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Viết đúng là "chăm sóc" — "ch" và "s".',
      },
      {
        id: 'tv-w05-q24',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Từ nào dưới đây chỉ người trong gia đình?',
        options: ['ông bà', 'bàn ghế', 'sân trường', 'chạy nhảy'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '"ông bà" là người trong gia đình.',
      },
      {
        id: 'tv-w05-q25',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Từ nào dưới đây KHÔNG chỉ người trong gia đình?',
        options: ['cha mẹ', 'anh chị', 'cô giáo', 'em trai'],
        correctAnswer: 2,
        rewardMinutes: 2,
        explanation: '"cô giáo" là người ở trường, không phải người trong gia đình.',
      },
      {
        id: 'tv-w05-q6',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Mẹ của mẹ em gọi là gì?',
        options: ['bà ngoại', 'bà nội', 'cô', 'dì'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Mẹ của mẹ là bà ngoại.',
      },
      {
        id: 'tv-w05-q7',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Mẹ của bố em gọi là gì?',
        options: ['bà nội', 'bà ngoại', 'bác', 'thím'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Mẹ của bố là bà nội.',
      },
      {
        id: 'tv-w05-q8',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Em gái của bố em thường được gọi là gì?',
        options: ['cô', 'dì', 'bà', 'chị'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Em gái của bố gọi là cô.',
      },
      {
        id: 'tv-w05-q9',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Em gái của mẹ em thường được gọi là gì?',
        options: ['dì', 'cô', 'bác', 'chú'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Em gái của mẹ gọi là dì.',
      },
      {
        id: 'tv-w05-q10',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Nhóm từ nào dưới đây đều chỉ tình cảm gia đình?',
        options: ['yêu thương, kính trọng, hiếu thảo', 'bàn, ghế, tủ', 'chạy, nhảy, bơi', 'xanh, đỏ, tím'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Cả ba từ đều nói về tình cảm với người thân.',
      },
      {
        id: 'tv-w05-q11',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Từ "hiếu thảo" dùng để nói về ai?',
        options: ['Con cháu đối với ông bà, cha mẹ', 'Bạn bè cùng lớp', 'Thầy cô với học sinh', 'Người bán hàng'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: '"Hiếu thảo" là lòng biết ơn của con cháu với ông bà, cha mẹ.',
      },
      {
        id: 'tv-w05-q12',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Điền từ thích hợp: "Em rất ... ông bà."',
        options: ['kính yêu', 'quét nhà', 'màu xanh', 'buổi sáng'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '"kính yêu" thể hiện tình cảm với ông bà.',
      },
      {
        id: 'tv-w05-q13',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Điền từ chỉ việc làm giúp gia đình: "Sau bữa cơm, em ... bát giúp mẹ."',
        options: ['rửa', 'ngọt', 'cao', 'bát'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '"rửa bát" là việc em làm giúp mẹ.',
      },
      {
        id: 'tv-w05-q14',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Việc nào dưới đây thể hiện em biết giúp đỡ gia đình?',
        options: ['Quét nhà, trông em', 'Bỏ dở bài tập', 'Bày bừa đồ chơi', 'Nói chuyện to khi ông bà ngủ'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Quét nhà và trông em là giúp đỡ bố mẹ.',
      },
      {
        id: 'tv-w05-q15',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Câu nào dưới đây thuộc mẫu "Ai làm gì?"',
        options: ['Bà em rất hiền.', 'Bà em kể chuyện cổ tích.', 'Bà em là giáo viên.', 'Bà em ơi!'],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation: '"kể chuyện cổ tích" là hoạt động của bà.',
      },
      {
        id: 'tv-w05-q16',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Câu nào dưới đây thuộc mẫu "Ai thế nào?"',
        options: ['Mẹ em rất dịu dàng.', 'Mẹ em nấu cơm.', 'Mẹ em là bác sĩ.', 'Mẹ ơi!'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '"rất dịu dàng" nêu đặc điểm của mẹ.',
      },
      {
        id: 'tv-w05-q17',
        subject: 'Tiếng Việt',
        skill: 'Tập đọc',
        passage:
          'Bà em đã già, lưng hơi còng nhưng giọng nói vẫn ấm áp. Bà thương hai chị em em nhất nhà. Buổi chiều bà ra vườn hái rau, còn mỗi tối bà lại kể cho hai chị em nghe một câu chuyện cổ tích.',
        content: 'Theo đoạn văn, bà thường làm gì cho hai chị em vào buổi tối?',
        options: ['Kể chuyện cổ tích', 'Dạy hát', 'Dẫn đi chơi', 'Nấu cơm'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Đoạn văn viết: "mỗi tối bà lại kể cho hai chị em nghe một câu chuyện cổ tích".',
      },
      {
        id: 'tv-w05-q18',
        subject: 'Tiếng Việt',
        skill: 'Chính tả',
        content: 'Từ nào dưới đây viết ĐÚNG chính tả?',
        options: ['hiếu thảo', 'hiếu thão', 'hiếu tảo', 'hiếu thảu'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Viết đúng là "hiếu thảo".',
      },
      {
        id: 'tv-w05-q19',
        subject: 'Tiếng Việt',
        skill: 'Chính tả',
        content: 'Từ nào dưới đây viết ĐÚNG chính tả?',
        options: ['dịu dàng', 'giu dàng', 'rịu dàng', 'dịu ràng'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Viết đúng là "dịu dàng".',
      },
      {
        id: 'tv-w05-q20',
        subject: 'Tiếng Việt',
        skill: 'Chính tả',
        content: 'Từ nào dưới đây viết SAI chính tả?',
        options: ['ông bà', 'cha mẹ', 'anh chị', 'em chai'],
        correctAnswer: 3,
        rewardMinutes: 2,
        explanation: '"em chai" sai, phải viết là "em trai".',
      },
      {
        id: 'tv-w05-q21',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Từ nào gần nghĩa với "thương yêu"?',
        options: ['yêu mến', 'ghét bỏ', 'xa lạ', 'lạnh nhạt'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: '"thương yêu" và "yêu mến" cùng chỉ tình cảm tốt.',
      },
      {
        id: 'tv-w05-q22',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Trong câu "Cả nhà em quây quần bên mâm cơm.", từ nào chỉ hoạt động?',
        options: ['Cả nhà em', 'quây quần', 'mâm cơm', 'bên'],
        correctAnswer: 1,
        rewardMinutes: 3,
        explanation: '"quây quần" là việc mọi người đang làm.',
      },
      {
        id: 'tv-w05-q23',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Người sinh ra bố và mẹ em được gọi chung là gì?',
        options: ['ông bà', 'cô dì', 'chú bác', 'anh chị'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Ông bà là người sinh ra bố mẹ em.',
      },
],
  },
  {
    subject: 'Tiếng Việt',
    weekNumber: 6,
    unit: UNIT_2,
    title: 'Biện pháp so sánh',
    difficulty: 1,
    questions: [
      {
        id: 'tv-12',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content:
          'Trong câu "Mắt em bé sáng như ngôi sao.", sự vật nào được so sánh với ngôi sao?',
        options: ['em bé', 'ngôi sao', 'ánh sáng', 'mắt em bé'],
        correctAnswer: 3,
        rewardMinutes: 3,
        explanation: '"Mắt em bé" được so sánh với "ngôi sao" qua từ so sánh "như".',
      },
      {
        id: 'tv-w06-q1',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Từ nào dưới đây là TỪ SO SÁNH?',
        options: ['như', 'và', 'nhưng', 'rồi'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Các từ so sánh thường gặp: như, là, tựa, giống như, chẳng bằng.',
      },
      {
        id: 'tv-w06-q2',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Câu nào dưới đây CÓ hình ảnh so sánh?',
        options: [
          'Trăng tròn như cái đĩa.',
          'Trăng lên cao rồi.',
          'Em rất thích ngắm trăng.',
          'Đêm nay trời nhiều mây.',
        ],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '"Trăng" được so sánh với "cái đĩa" qua từ "như".',
      },
      {
        id: 'tv-w06-q3',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Điền từ so sánh thích hợp: "Tiếng suối trong ... tiếng hát xa."',
        options: ['và', 'như', 'nhưng', 'còn'],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation: 'Dùng "như" để so sánh tiếng suối với tiếng hát.',
      },
      {
        id: 'tv-w06-q4',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Trong câu "Cô giáo là người mẹ hiền.", từ nào dùng để so sánh?',
        options: ['Cô giáo', 'là', 'người mẹ', 'hiền'],
        correctAnswer: 1,
        rewardMinutes: 3,
        explanation: 'Ở đây từ "là" đóng vai trò từ so sánh, ví cô giáo với người mẹ hiền.',
      },
      {
        id: 'tv-w06-q24',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Từ nào thường dùng để so sánh?',
        options: ['như', 'và', 'nhưng', 'thì'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Từ "như" dùng để so sánh hai sự vật.',
      },
      {
        id: 'tv-w06-q5',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Câu nào dưới đây có hình ảnh so sánh?',
        options: ['Trăng tròn như cái đĩa.', 'Trăng đã lên cao.', 'Em ngắm trăng.', 'Trăng sáng.'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: '"tròn như cái đĩa" là hình ảnh so sánh.',
      },
      {
        id: 'tv-w06-q6',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Trong câu "Mắt bé đen như hạt nhãn.", hai sự vật nào được so sánh?',
        options: ['Mắt bé và hạt nhãn', 'Bé và mẹ', 'Mắt và mũi', 'Hạt nhãn và quả nhãn'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Mắt bé được so sánh với hạt nhãn.',
      },
      {
        id: 'tv-w06-q7',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Trong câu "Tiếng suối trong như tiếng hát xa.", từ so sánh là từ nào?',
        options: ['trong', 'như', 'xa', 'tiếng'],
        correctAnswer: 1,
        rewardMinutes: 3,
        explanation: 'Từ so sánh là "như".',
      },
      {
        id: 'tv-w06-q8',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Điền từ để hoàn thành hình ảnh so sánh: "Cánh diều mềm mại ... cánh bướm."',
        options: ['như', 'của', 'ở', 'rồi'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Dùng từ "như" để so sánh cánh diều với cánh bướm.',
      },
      {
        id: 'tv-w06-q9',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Chọn hình ảnh so sánh phù hợp: "Hai bàn tay em trắng như ..."',
        options: ['hoa đầu cành', 'hòn than', 'bầu trời đêm', 'mực đen'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Trắng thì so sánh với hoa, không so sánh với than hay mực (màu đen).',
      },
      {
        id: 'tv-w06-q10',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Chọn hình ảnh so sánh phù hợp: "Mặt trời đỏ rực như ..."',
        options: ['quả cầu lửa', 'tờ giấy trắng', 'hòn tuyết', 'cái bảng đen'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Đỏ rực nên so sánh với quả cầu lửa.',
      },
      {
        id: 'tv-w06-q11',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Câu nào KHÔNG có hình ảnh so sánh?',
        options: ['Ông trăng tròn như quả bóng.', 'Da mẹ trắng như trứng gà bóc.', 'Em rất yêu mẹ của em.', 'Lá cọ xoè ra như bàn tay.'],
        correctAnswer: 2,
        rewardMinutes: 3,
        explanation: 'Câu đó chỉ nói tình cảm, không so sánh hai sự vật.',
      },
      {
        id: 'tv-w06-q12',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Trong câu "Cánh đồng rộng như một tấm thảm vàng.", cánh đồng được so sánh với gì?',
        options: ['Tấm thảm vàng', 'Con đường', 'Dòng sông', 'Ngọn núi'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Cánh đồng được so sánh với tấm thảm vàng.',
      },
      {
        id: 'tv-w06-q13',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Từ nào dưới đây cũng dùng để so sánh?',
        options: ['là', 'tựa như', 'nếu', 'vì'],
        correctAnswer: 1,
        rewardMinutes: 3,
        explanation: '"tựa như" là từ so sánh, giống như "như", "giống".',
      },
      {
        id: 'tv-w06-q14',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Câu "Cô giáo như mẹ hiền." so sánh cô giáo với ai?',
        options: ['Mẹ hiền', 'Bà ngoại', 'Chị gái', 'Bạn bè'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Cô giáo được so sánh với mẹ hiền.',
      },
      {
        id: 'tv-w06-q15',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Hình ảnh so sánh giúp câu văn thế nào?',
        options: ['Sinh động, dễ hình dung hơn', 'Dài dòng và khó hiểu', 'Sai chính tả', 'Ít từ hơn'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'So sánh làm câu văn sinh động, gợi hình.',
      },
      {
        id: 'tv-w06-q16',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Chọn từ so sánh đúng: "Bé ngoan ... con mèo nhỏ."',
        options: ['như', 'và', 'hoặc', 'song'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Dùng "như" để so sánh.',
      },
      {
        id: 'tv-w06-q17',
        subject: 'Tiếng Việt',
        skill: 'Tập đọc',
        passage:
          'Tiếng suối trong như tiếng hát xa\nTrăng lồng cổ thụ bóng lồng hoa\nCảnh khuya như vẽ người chưa ngủ\nChưa ngủ vì lo nỗi nước nhà.',
        content: 'Theo đoạn thơ, tiếng suối được so sánh với gì?',
        options: ['Tiếng hát xa', 'Tiếng chim', 'Tiếng đàn', 'Tiếng mưa'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Đoạn thơ viết: "Tiếng suối trong như tiếng hát xa".',
      },
      {
        id: 'tv-w06-q18',
        subject: 'Tiếng Việt',
        skill: 'Tập đọc',
        passage:
          'Tiếng suối trong như tiếng hát xa\nTrăng lồng cổ thụ bóng lồng hoa\nCảnh khuya như vẽ người chưa ngủ\nChưa ngủ vì lo nỗi nước nhà.',
        content: 'Theo đoạn thơ, trăng lồng vào đâu?',
        options: ['Cổ thụ', 'Mặt nước', 'Mái nhà', 'Cánh đồng'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Đoạn thơ viết: "Trăng lồng cổ thụ bóng lồng hoa".',
      },
      {
        id: 'tv-w06-q19',
        subject: 'Tiếng Việt',
        skill: 'Chính tả',
        content: 'Từ nào dưới đây viết ĐÚNG chính tả?',
        options: ['so sánh', 'xo sánh', 'so xánh', 'xo xánh'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Viết đúng là "so sánh".',
      },
      {
        id: 'tv-w06-q20',
        subject: 'Tiếng Việt',
        skill: 'Chính tả',
        content: 'Từ nào dưới đây viết ĐÚNG chính tả?',
        options: ['trong trẻo', 'chong chẻo', 'trong chẻo', 'chong trẻo'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Viết đúng là "trong trẻo".',
      },
      {
        id: 'tv-w06-q21',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Câu nào dùng hình ảnh so sánh HỢP LÍ?',
        options: ['Bé cười tươi như hoa.', 'Bé cười tươi như hòn đá.', 'Bé cười tươi như cái ghế.', 'Bé cười tươi như chiếc cặp.'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Nụ cười tươi thường được so sánh với hoa.',
      },
      {
        id: 'tv-w06-q22',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Trong câu "Những ngôi sao lấp lánh như mắt trời.", sự vật nào được so sánh?',
        options: ['Những ngôi sao', 'Mặt đất', 'Dòng sông', 'Cánh đồng'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Những ngôi sao được so sánh với "mắt trời".',
      },
      {
        id: 'tv-w06-q23',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Từ nào dưới đây KHÔNG phải từ so sánh?',
        options: ['như', 'giống như', 'tựa như', 'bởi vì'],
        correctAnswer: 3,
        rewardMinutes: 2,
        explanation: '"bởi vì" chỉ nguyên nhân, không dùng để so sánh.',
      },
],
  },
  {
    subject: 'Tiếng Việt',
    weekNumber: 7,
    unit: UNIT_2,
    title: 'Chính tả phân biệt ch/tr',
    difficulty: 1,
    questions: [
      {
        id: 'tv-10',
        subject: 'Tiếng Việt',
        skill: 'Chính tả',
        content: 'Từ nào dưới đây viết ĐÚNG chính tả?',
        options: ['che chở', 'tre chở', 'che trở', 'tre trở'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Viết đúng là "che chở" (nghĩa là bảo vệ, giúp đỡ).',
      },
      {
        id: 'tv-w07-q1',
        subject: 'Tiếng Việt',
        skill: 'Chính tả',
        content: 'Điền vào chỗ trống: "Bà ...ồng rau ngoài vườn."',
        options: ['ch', 'tr', 'nh', 'gi'],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation: 'Viết đúng là "trồng rau".',
      },
      {
        id: 'tv-w07-q2',
        subject: 'Tiếng Việt',
        skill: 'Chính tả',
        content: 'Từ nào dưới đây viết ĐÚNG chính tả?',
        options: ['chung thuỷ', 'trung thuỷ', 'chung thủi', 'trung thủi'],
        correctAnswer: 0,
        rewardMinutes: 3,
        explanation: 'Viết đúng là "chung thuỷ".',
      },
      {
        id: 'tv-w07-q3',
        subject: 'Tiếng Việt',
        skill: 'Chính tả',
        content: 'Cây ... mọc thành bụi, thân có đốt. Điền từ đúng:',
        options: ['che', 'tre', 'chè', 'trè'],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation: '"Cây tre" thân có đốt, mọc thành bụi.',
      },
      {
        id: 'tv-w07-q4',
        subject: 'Tiếng Việt',
        skill: 'Chính tả',
        content: 'Từ nào dưới đây viết SAI chính tả?',
        options: ['trò chuyện', 'chăm chỉ', 'trong trẻo', 'trân thành'],
        correctAnswer: 3,
        rewardMinutes: 3,
        explanation:
          '"trân thành" sai, phải viết là "chân thành". Ba từ còn lại đều đúng.',
      },
    ],
  },
  {
    subject: 'Tiếng Việt',
    weekNumber: 8,
    unit: UNIT_2,
    title: 'Từ chỉ tình cảm và lòng nhân ái',
    difficulty: 1,
    questions: [
      {
        id: 'tv-w08-q1',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Từ nào dưới đây nói về lòng tốt với người khác?',
        options: ['ích kỉ', 'nhân hậu', 'lười biếng', 'cẩu thả'],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation: '"nhân hậu" là hiền lành, thương người.',
      },
      {
        id: 'tv-w08-q2',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Từ nào TRÁI NGHĨA với "yêu thương"?',
        options: ['quý mến', 'thương yêu', 'ghét bỏ', 'chăm sóc'],
        correctAnswer: 2,
        rewardMinutes: 2,
        explanation: '"ghét bỏ" trái nghĩa với "yêu thương".',
      },
      {
        id: 'tv-w08-q3',
        subject: 'Tiếng Việt',
        skill: 'Tập đọc',
        passage:
          'Trên đường đi học về, Lan thấy một cụ già đang loay hoay qua đường. Lan chạy tới, nắm tay cụ và dắt cụ sang bên kia đường. Cụ mỉm cười cảm ơn Lan.',
        content: 'Việc làm của Lan cho thấy bạn ấy là người thế nào?',
        options: [
          'Nhút nhát',
          'Biết giúp đỡ người khác',
          'Ham chơi',
          'Cẩu thả',
        ],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation: 'Lan chủ động dắt cụ già qua đường, đó là hành động giúp đỡ người khác.',
      },
      {
        id: 'tv-w08-q4',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Chọn từ thích hợp: "Các bạn trong lớp luôn ... nhau khi gặp khó khăn."',
        options: ['trêu chọc', 'giúp đỡ', 'tranh giành', 'bỏ mặc'],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation: '"giúp đỡ" phù hợp với ý nghĩa tốt đẹp của câu.',
      },
      {
        id: 'tv-w08-q5',
        subject: 'Tiếng Việt',
        skill: 'Chính tả',
        content: 'Từ nào dưới đây viết ĐÚNG chính tả?',
        options: ['sẻ chia', 'xẻ chia', 'sẻ tria', 'xẻ tria'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Viết đúng là "sẻ chia" (cũng có thể nói "chia sẻ").',
      },
    ],
  },
  {
    subject: 'Tiếng Việt',
    weekNumber: 9,
    unit: UNIT_2,
    title: 'Chính tả phân biệt s/x',
    difficulty: 1,
    questions: [
      {
        id: 'tv-02',
        subject: 'Tiếng Việt',
        skill: 'Chính tả',
        content: 'Từ nào dưới đây viết ĐÚNG chính tả?',
        options: ['xanh xao', 'sanh sao', 'xanh sao', 'sanh xao'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Viết đúng là "xanh xao" (cả hai tiếng đều bắt đầu bằng "x").',
      },
      {
        id: 'tv-w09-q1',
        subject: 'Tiếng Việt',
        skill: 'Chính tả',
        content: 'Điền vào chỗ trống: "Buổi ...áng, em dậy sớm tập thể dục."',
        options: ['s', 'x', 'ch', 'tr'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Viết đúng là "buổi sáng".',
      },
      {
        id: 'tv-w09-q2',
        subject: 'Tiếng Việt',
        skill: 'Chính tả',
        content: 'Từ nào dưới đây viết ĐÚNG chính tả?',
        options: ['xúc động', 'súc động', 'xúc đông', 'súc đông'],
        correctAnswer: 0,
        rewardMinutes: 2,
        explanation: 'Viết đúng là "xúc động".',
      },
      {
        id: 'tv-w09-q3',
        subject: 'Tiếng Việt',
        skill: 'Chính tả',
        content: 'Từ nào dưới đây viết ĐÚNG chính tả?',
        options: ['sạch xẽ', 'xạch sẽ', 'sạch sẽ', 'xạch xẽ'],
        correctAnswer: 2,
        rewardMinutes: 2,
        explanation: 'Viết đúng là "sạch sẽ" — cả hai tiếng đều bắt đầu bằng "s".',
      },
      {
        id: 'tv-w09-q4',
        subject: 'Tiếng Việt',
        skill: 'Chính tả',
        content: 'Con vật nào viết đúng chính tả?',
        options: ['con xâu', 'con sâu', 'con xâo', 'con sâo'],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation: 'Viết đúng là "con sâu".',
      },
    ],
  },
  {
    subject: 'Tiếng Việt',
    weekNumber: 10,
    unit: UNIT_2,
    title: 'Ôn tập giữa học kì 1',
    difficulty: 1,
    questions: [
      {
        id: 'tv-w10-q1',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Câu "Ngôi trường của em rất khang trang." thuộc mẫu câu nào?',
        options: ['Ai là gì?', 'Ai làm gì?', 'Ai thế nào?', 'Ở đâu?'],
        correctAnswer: 2,
        rewardMinutes: 2,
        explanation: '"rất khang trang" nêu đặc điểm của ngôi trường.',
      },
      {
        id: 'tv-w10-q2',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Câu nào dưới đây CÓ hình ảnh so sánh?',
        options: [
          'Em bé ngủ rất ngoan.',
          'Da em bé mịn như nhung.',
          'Em bé đang tập đi.',
          'Mẹ bế em bé.',
        ],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation: '"Da em bé" được so sánh với "nhung" qua từ "như".',
      },
      {
        id: 'tv-w10-q3',
        subject: 'Tiếng Việt',
        skill: 'Chính tả',
        content: 'Từ nào dưới đây viết ĐÚNG chính tả?',
        options: ['nàng xóm', 'làng sóm', 'làng xóm', 'nàng sóm'],
        correctAnswer: 2,
        rewardMinutes: 2,
        explanation: 'Viết đúng là "làng xóm" — "l" và "x".',
      },
      {
        id: 'tv-w10-q4',
        subject: 'Tiếng Việt',
        skill: 'Tập đọc',
        passage:
          'Mùa thu, hàng cây bên đường thay áo mới. Lá vàng rụng đầy vỉa hè. Mỗi cơn gió đi qua lại cuốn lá bay lên, xoay tròn rồi nhẹ nhàng đáp xuống.',
        content: 'Đoạn văn tả cảnh vật vào mùa nào?',
        options: ['Mùa xuân', 'Mùa hạ', 'Mùa thu', 'Mùa đông'],
        correctAnswer: 2,
        rewardMinutes: 2,
        explanation: 'Câu đầu tiên đã nêu rõ: "Mùa thu, hàng cây bên đường thay áo mới".',
      },
      {
        id: 'tv-w10-q5',
        subject: 'Tiếng Việt',
        skill: 'Luyện từ và câu',
        content: 'Từ nào dưới đây là từ chỉ đặc điểm?',
        options: ['ngôi nhà', 'rộng rãi', 'quét dọn', 'buổi chiều'],
        correctAnswer: 1,
        rewardMinutes: 2,
        explanation: '"rộng rãi" tả đặc điểm về kích thước.',
      },
    ],
  },

  /* ====== TUẦN 11-18: QUÊ HƯƠNG ĐẤT NƯỚC ====== */
  {
    subject: 'Tiếng Việt', weekNumber: 11, unit: UNIT_3,
    title: 'Từ ngữ về cảnh đẹp quê hương', difficulty: 2,
    questions: [
      { id: 'tv-w11-q1', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Nhóm từ nào dưới đây đều tả cảnh đẹp thiên nhiên?',
        options: ['núi non, sông nước, biển cả', 'bàn ghế, sách vở, bút mực',
          'bác sĩ, kĩ sư, giáo viên', 'chạy nhảy, học bài, quét nhà'],
        correctAnswer: 0, rewardMinutes: 3,
        explanation: 'Núi non, sông nước, biển cả đều là cảnh vật thiên nhiên.' },
      { id: 'tv-w11-q2', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Chọn từ tả cảnh đẹp để điền: "Dòng sông quê em ... uốn quanh làng."',
        options: ['ồn ào', 'hiền hoà', 'lười biếng', 'vội vàng'],
        correctAnswer: 1, rewardMinutes: 3,
        explanation: '"hiền hoà" tả dòng sông êm đềm, hợp với cảnh làng quê.' },
      { id: 'tv-w11-q3', subject: 'Tiếng Việt', skill: 'Tập đọc',
        passage: 'Quê em có cánh đồng lúa rộng mênh mông. Mỗi khi gió thổi, sóng lúa lại nhấp nhô như mặt biển vàng. Xa xa, luỹ tre xanh ôm lấy xóm làng.',
        content: 'Cánh đồng lúa khi có gió được so sánh với gì?',
        options: ['Mặt biển vàng', 'Luỹ tre xanh', 'Xóm làng', 'Bầu trời'],
        correctAnswer: 0, rewardMinutes: 3,
        explanation: 'Đoạn văn viết: "sóng lúa lại nhấp nhô như mặt biển vàng".' },
    ],
  },
  {
    subject: 'Tiếng Việt', weekNumber: 12, unit: UNIT_3,
    title: 'Biện pháp nhân hoá', difficulty: 2,
    questions: [
      { id: 'tv-13', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Câu nào dưới đây có dùng biện pháp NHÂN HOÁ?',
        options: ['Trời rất tối.', 'Mây có màu xám.',
          'Ông trời mặc áo giáp đen ra trận.', 'Mưa rơi rất to.'],
        correctAnswer: 2, rewardMinutes: 3,
        explanation: 'Trời được gọi là "ông" và biết "mặc áo giáp ra trận" như người — đó là nhân hoá.' },
      { id: 'tv-w12-q1', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Nhân hoá là gọi hoặc tả sự vật bằng cách nào?',
        options: ['Bằng những từ dùng cho con người', 'Bằng cách so sánh với sự vật khác',
          'Bằng cách kể lại câu chuyện', 'Bằng cách đặt câu hỏi'],
        correctAnswer: 0, rewardMinutes: 3,
        explanation: 'Nhân hoá là dùng từ ngữ vốn tả người để gọi hoặc tả vật.' },
      { id: 'tv-w12-q2', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Câu nào dưới đây KHÔNG dùng nhân hoá?',
        options: ['Chị gió đùa nghịch ngoài sân.', 'Bác mặt trời đạp xe qua đỉnh núi.',
          'Cây bàng đứng lặng lẽ trong mưa.', 'Trên sân có mấy chiếc lá rụng.'],
        correctAnswer: 3, rewardMinutes: 3,
        explanation: 'Câu cuối chỉ kể sự việc bình thường, không gán đặc điểm của người cho vật.' },
    ],
  },
  {
    subject: 'Tiếng Việt', weekNumber: 13, unit: UNIT_3,
    title: 'Dấu chấm và dấu chấm hỏi', difficulty: 2,
    questions: [
      { id: 'tv-14', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Cuối câu kể "Em rất thích đọc truyện" cần đặt dấu câu nào?',
        options: ['dấu chấm', 'dấu chấm hỏi', 'dấu chấm than', 'dấu phẩy'],
        correctAnswer: 0, rewardMinutes: 2,
        explanation: 'Câu kể thì kết thúc bằng dấu chấm.' },
      { id: 'tv-w13-q1', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Cuối câu "Bạn có thích môn Toán không" cần đặt dấu gì?',
        options: ['dấu chấm', 'dấu chấm hỏi', 'dấu phẩy', 'dấu hai chấm'],
        correctAnswer: 1, rewardMinutes: 2,
        explanation: 'Đây là câu hỏi nên kết thúc bằng dấu chấm hỏi.' },
      { id: 'tv-w13-q2', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Câu "Ôi, bông hoa đẹp quá" nên kết thúc bằng dấu gì?',
        options: ['dấu chấm', 'dấu chấm hỏi', 'dấu chấm than', 'dấu hai chấm'],
        correctAnswer: 2, rewardMinutes: 3,
        explanation: 'Câu bộc lộ cảm xúc (câu cảm) thì kết thúc bằng dấu chấm than.' },
    ],
  },
  {
    subject: 'Tiếng Việt', weekNumber: 14, unit: UNIT_3,
    title: 'Bộ phận trả lời câu hỏi "Ở đâu?"', difficulty: 2,
    questions: [
      { id: 'tv-17', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Trong câu "Các bạn học sinh chơi bóng ở sân trường.", bộ phận nào trả lời cho câu hỏi "Ở đâu?"',
        options: ['Các bạn học sinh', 'ở sân trường', 'chơi bóng', 'bóng'],
        correctAnswer: 1, rewardMinutes: 3,
        explanation: '"ở sân trường" chỉ địa điểm nên trả lời cho câu hỏi "Ở đâu?".' },
      { id: 'tv-w14-q1', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Đặt câu hỏi cho bộ phận in đậm: "Chim hót líu lo TRÊN CÀNH CÂY."',
        options: ['Ai?', 'Làm gì?', 'Ở đâu?', 'Khi nào?'],
        correctAnswer: 2, rewardMinutes: 3,
        explanation: '"trên cành cây" chỉ nơi chốn nên hỏi bằng "Ở đâu?".' },
      { id: 'tv-w14-q2', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Bộ phận nào trả lời cho câu hỏi "Khi nào?" trong câu "Sáng sớm, em cùng bố tập thể dục."',
        options: ['Sáng sớm', 'em cùng bố', 'tập thể dục', 'bố'],
        correctAnswer: 0, rewardMinutes: 3,
        explanation: '"Sáng sớm" chỉ thời gian nên trả lời cho câu hỏi "Khi nào?".' },
    ],
  },
  {
    subject: 'Tiếng Việt', weekNumber: 15, unit: UNIT_3,
    title: 'Dấu phẩy và dấu hai chấm', difficulty: 2,
    questions: [
      { id: 'tv-20', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Trong câu: Bạn Nam nói: "Mình rất thích môn Toán." — dấu hai chấm dùng để làm gì?',
        options: ['báo hiệu lời nói của nhân vật', 'kết thúc câu kể',
          'ngăn cách các từ cùng loại', 'dùng để hỏi'],
        correctAnswer: 0, rewardMinutes: 3,
        explanation: 'Dấu hai chấm ở đây báo hiệu phần tiếp theo là lời nói của bạn Nam.' },
      { id: 'tv-w15-q1', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Dấu phẩy trong câu "Vườn nhà em trồng cam, quýt, bưởi." dùng để làm gì?',
        options: ['Ngăn cách các từ cùng loại', 'Báo hiệu lời nói',
          'Kết thúc câu', 'Thể hiện cảm xúc'],
        correctAnswer: 0, rewardMinutes: 3,
        explanation: 'Dấu phẩy ngăn cách các từ cùng chỉ loại quả trong câu.' },
      { id: 'tv-w15-q2', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Câu nào dưới đây đặt dấu phẩy ĐÚNG?',
        options: ['Trên sân trường các bạn, đang chơi nhảy dây.',
          'Trên sân trường, các bạn đang chơi nhảy dây.',
          'Trên, sân trường các bạn đang chơi nhảy dây.',
          'Trên sân trường các bạn đang, chơi nhảy dây.'],
        correctAnswer: 1, rewardMinutes: 3,
        explanation: 'Dấu phẩy đặt sau bộ phận chỉ nơi chốn "Trên sân trường".' },
    ],
  },
  {
    subject: 'Tiếng Việt', weekNumber: 16, unit: UNIT_3,
    title: 'Chính tả phân biệt iê/yê', difficulty: 2,
    questions: [
      { id: 'tv-w16-q1', subject: 'Tiếng Việt', skill: 'Chính tả',
        content: 'Từ nào dưới đây viết ĐÚNG chính tả?',
        options: ['yêu thương', 'iêu thương', 'yiêu thương', 'iu thương'],
        correctAnswer: 0, rewardMinutes: 3,
        explanation: 'Viết "yê" khi đứng đầu tiếng: yêu thương, yên tĩnh.' },
      { id: 'tv-w16-q2', subject: 'Tiếng Việt', skill: 'Chính tả',
        content: 'Từ nào dưới đây viết ĐÚNG chính tả?',
        options: ['tiếng chim', 'tyếng chim', 'tiêng chim', 'tyêng chim'],
        correctAnswer: 0, rewardMinutes: 3,
        explanation: 'Viết "iê" khi có phụ âm đầu: tiếng, biển, chiếc.' },
      { id: 'tv-w16-q3', subject: 'Tiếng Việt', skill: 'Chính tả',
        content: 'Từ nào dưới đây viết ĐÚNG chính tả?',
        options: ['iên lặng', 'yên lặng', 'yiên lặng', 'iêng lặng'],
        correctAnswer: 1, rewardMinutes: 3,
        explanation: '"yên lặng" — tiếng "yên" không có phụ âm đầu nên viết "yê".' },
    ],
  },
  {
    subject: 'Tiếng Việt', weekNumber: 17, unit: UNIT_3,
    title: 'Câu khiến và câu cảm', difficulty: 2,
    questions: [
      { id: 'tv-w17-q1', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Câu nào dưới đây là CÂU KHIẾN (đề nghị, yêu cầu)?',
        options: ['Bạn hãy giữ trật tự nhé!', 'Bạn Lan học rất giỏi.',
          'Hôm nay trời đẹp quá!', 'Bạn có đi học không?'],
        correctAnswer: 0, rewardMinutes: 3,
        explanation: 'Câu khiến thường có các từ: hãy, đừng, chớ, nên, nhé...' },
      { id: 'tv-w17-q2', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Câu nào dưới đây là CÂU CẢM (bộc lộ cảm xúc)?',
        options: ['Em đi học lúc 7 giờ.', 'Ôi, cảnh biển đẹp quá!',
          'Bạn tên là gì?', 'Hãy đóng cửa lại.'],
        correctAnswer: 1, rewardMinutes: 3,
        explanation: 'Câu cảm thường có: ôi, chao, quá, thật... và kết thúc bằng dấu chấm than.' },
      { id: 'tv-w17-q3', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Từ nào thường xuất hiện trong câu khiến?',
        options: ['hãy', 'ôi', 'chao', 'không'],
        correctAnswer: 0, rewardMinutes: 3,
        explanation: '"hãy" dùng để yêu cầu, đề nghị người khác làm việc gì đó.' },
    ],
  },
  {
    subject: 'Tiếng Việt', weekNumber: 18, unit: UNIT_3,
    title: 'Ôn tập cuối học kì 1', difficulty: 2,
    questions: [
      { id: 'tv-w18-q1', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Câu "Bác mặt trời tươi cười nhìn xuống cánh đồng." dùng biện pháp gì?',
        options: ['So sánh', 'Nhân hoá', 'Không dùng biện pháp nào', 'Cả so sánh và nhân hoá'],
        correctAnswer: 1, rewardMinutes: 3,
        explanation: 'Mặt trời được gọi là "bác" và biết "tươi cười" như người — đó là nhân hoá.' },
      { id: 'tv-w18-q2', subject: 'Tiếng Việt', skill: 'Chính tả',
        content: 'Từ nào dưới đây viết ĐÚNG chính tả?',
        options: ['chiến sĩ', 'chiến sỹ', 'triến sĩ', 'chyến sĩ'],
        correctAnswer: 0, rewardMinutes: 3,
        explanation: 'Viết đúng là "chiến sĩ".' },
      { id: 'tv-w18-q3', subject: 'Tiếng Việt', skill: 'Tập đọc',
        passage: 'Đêm giao thừa, cả nhà quây quần bên nồi bánh chưng. Bếp lửa bập bùng soi rõ khuôn mặt ai cũng rạng rỡ. Ngoài sân, mưa xuân lất phất bay.',
        content: 'Đoạn văn tả khung cảnh vào dịp nào?',
        options: ['Ngày khai giảng', 'Đêm giao thừa', 'Ngày Trung thu', 'Buổi tổng kết năm học'],
        correctAnswer: 1, rewardMinutes: 3,
        explanation: 'Câu đầu đã nêu: "Đêm giao thừa, cả nhà quây quần bên nồi bánh chưng".' },
    ],
  },

  /* ====== TUẦN 19-27: NGHỆ THUẬT & SÁNG TẠO ====== */
  {
    subject: 'Tiếng Việt', weekNumber: 19, unit: UNIT_4,
    title: 'Từ ngữ về nghệ thuật', difficulty: 2,
    questions: [
      { id: 'tv-w19-q1', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Nhóm từ nào dưới đây đều chỉ người làm nghệ thuật?',
        options: ['ca sĩ, hoạ sĩ, nhạc sĩ', 'bác sĩ, y tá, dược sĩ',
          'nông dân, công nhân, thợ xây', 'học sinh, giáo viên, hiệu trưởng'],
        correctAnswer: 0, rewardMinutes: 3,
        explanation: 'Ca sĩ, hoạ sĩ, nhạc sĩ đều hoạt động trong lĩnh vực nghệ thuật.' },
      { id: 'tv-w19-q2', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Người vẽ tranh được gọi là gì?',
        options: ['nhạc sĩ', 'hoạ sĩ', 'ca sĩ', 'diễn viên'],
        correctAnswer: 1, rewardMinutes: 3,
        explanation: '"hoạ sĩ" là người vẽ tranh.' },
      { id: 'tv-w19-q3', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Từ nào dưới đây chỉ HOẠT ĐỘNG nghệ thuật?',
        options: ['cây đàn', 'biểu diễn', 'sân khấu', 'khán giả'],
        correctAnswer: 1, rewardMinutes: 3,
        explanation: '"biểu diễn" là việc làm, nên là từ chỉ hoạt động.' },
    ],
  },
  {
    subject: 'Tiếng Việt', weekNumber: 20, unit: UNIT_4,
    title: 'Mở rộng vốn từ: đồng nghĩa và trái nghĩa', difficulty: 2,
    questions: [
      { id: 'tv-16', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Từ nào dưới đây CÙNG NGHĨA với từ "to"?',
        options: ['nhỏ', 'bé', 'lớn', 'thấp'],
        correctAnswer: 2, rewardMinutes: 2,
        explanation: '"lớn" cùng nghĩa với "to". "nhỏ" và "bé" là trái nghĩa.' },
      { id: 'tv-04', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Từ nào TRÁI NGHĨA với từ "siêng năng"?',
        options: ['chăm chỉ', 'cần mẫn', 'lười biếng', 'nhanh nhẹn'],
        correctAnswer: 2, rewardMinutes: 2,
        explanation: '"lười biếng" trái nghĩa với "siêng năng". "chăm chỉ" và "cần mẫn" lại cùng nghĩa.' },
      { id: 'tv-w20-q1', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Cặp từ nào dưới đây là cặp TRÁI NGHĨA?',
        options: ['vui — buồn', 'to — lớn', 'đẹp — xinh', 'nhanh — mau'],
        correctAnswer: 0, rewardMinutes: 3,
        explanation: '"vui" và "buồn" trái ngược nhau; ba cặp còn lại đều cùng nghĩa.' },
    ],
  },
  {
    subject: 'Tiếng Việt', weekNumber: 21, unit: UNIT_4,
    title: 'Câu hỏi "Vì sao?" và "Để làm gì?"', difficulty: 2,
    questions: [
      { id: 'tv-15', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Câu "Vì trời mưa nên em không đi chơi." trả lời cho câu hỏi nào?',
        options: ['Ở đâu?', 'Khi nào?', 'Bằng gì?', 'Vì sao?'],
        correctAnswer: 3, rewardMinutes: 3,
        explanation: 'Bộ phận "Vì trời mưa" nêu lí do nên trả lời cho câu hỏi "Vì sao?".' },
      { id: 'tv-w21-q1', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Bộ phận nào trả lời cho câu hỏi "Để làm gì?" trong câu "Em học chăm để bố mẹ vui lòng."',
        options: ['Em', 'học chăm', 'để bố mẹ vui lòng', 'bố mẹ'],
        correctAnswer: 2, rewardMinutes: 3,
        explanation: '"để bố mẹ vui lòng" nêu mục đích của việc học chăm.' },
      { id: 'tv-w21-q2', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Từ nào dùng để nêu lí do?',
        options: ['vì', 'để', 'bằng', 'khi'],
        correctAnswer: 0, rewardMinutes: 3,
        explanation: '"vì", "bởi vì", "do" dùng để nêu lí do; "để" nêu mục đích.' },
    ],
  },
  {
    subject: 'Tiếng Việt', weekNumber: 22, unit: UNIT_4,
    title: 'Chính tả phân biệt d/gi/r', difficulty: 2,
    questions: [
      { id: 'tv-18', subject: 'Tiếng Việt', skill: 'Chính tả',
        content: 'Từ nào dưới đây viết ĐÚNG chính tả?',
        options: ['dúp đỡ', 'giúp đở', 'giúp đỡ', 'rúp đỡ'],
        correctAnswer: 2, rewardMinutes: 2,
        explanation: 'Viết đúng là "giúp đỡ" — "gi" và dấu ngã ở tiếng "đỡ".' },
      { id: 'tv-w22-q1', subject: 'Tiếng Việt', skill: 'Chính tả',
        content: 'Từ nào dưới đây viết ĐÚNG chính tả?',
        options: ['dòng sông', 'giòng sông', 'ròng sông', 'dòng xông'],
        correctAnswer: 0, rewardMinutes: 3,
        explanation: 'Viết đúng là "dòng sông".' },
      { id: 'tv-w22-q2', subject: 'Tiếng Việt', skill: 'Chính tả',
        content: 'Điền chữ đúng: "Trời ...ét quá, em mặc thêm áo."',
        options: ['d', 'gi', 'r', 'nh'],
        correctAnswer: 2, rewardMinutes: 3,
        explanation: 'Viết đúng là "rét" (lạnh).' },
    ],
  },
  {
    subject: 'Tiếng Việt', weekNumber: 23, unit: UNIT_4,
    title: 'Từ ngữ về thể thao', difficulty: 2,
    questions: [
      { id: 'tv-w23-q1', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Nhóm từ nào dưới đây đều là môn thể thao?',
        options: ['bóng đá, bơi lội, cầu lông', 'bóng đá, vẽ tranh, ca hát',
          'chạy bộ, nấu ăn, quét nhà', 'cờ vua, làm thơ, đọc sách'],
        correctAnswer: 0, rewardMinutes: 3,
        explanation: 'Bóng đá, bơi lội, cầu lông đều là môn thể thao.' },
      { id: 'tv-w23-q2', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Người thi đấu thể thao được gọi là gì?',
        options: ['khán giả', 'vận động viên', 'nhạc công', 'hoạ sĩ'],
        correctAnswer: 1, rewardMinutes: 3,
        explanation: '"vận động viên" là người tập luyện và thi đấu thể thao.' },
      { id: 'tv-w23-q3', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Chọn từ thích hợp: "Đội bóng lớp em đã ... trong trận chung kết."',
        options: ['chiến thắng', 'nấu nướng', 'vẽ tranh', 'ngủ say'],
        correctAnswer: 0, rewardMinutes: 3,
        explanation: '"chiến thắng" phù hợp với ngữ cảnh thi đấu thể thao.' },
    ],
  },
  {
    subject: 'Tiếng Việt', weekNumber: 24, unit: UNIT_4,
    title: 'Từ ngữ về lễ hội và văn hoá', difficulty: 3,
    questions: [
      { id: 'tv-w24-q1', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Hoạt động nào dưới đây thường có trong lễ hội?',
        options: ['rước kiệu', 'làm bài tập', 'quét lớp', 'đi ngủ'],
        correctAnswer: 0, rewardMinutes: 3,
        explanation: 'Rước kiệu là hoạt động quen thuộc trong các lễ hội truyền thống.' },
      { id: 'tv-w24-q2', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Tết Trung thu thường diễn ra vào thời gian nào trong năm?',
        options: ['Đầu mùa xuân', 'Giữa mùa thu', 'Đầu mùa hạ', 'Cuối mùa đông'],
        correctAnswer: 1, rewardMinutes: 3,
        explanation: 'Tết Trung thu là rằm tháng Tám âm lịch, vào giữa mùa thu.' },
      { id: 'tv-w24-q3', subject: 'Tiếng Việt', skill: 'Tập đọc',
        passage: 'Đêm rằm tháng Tám, trẻ con trong xóm rước đèn đi khắp ngõ. Tiếng trống ếch thùng thình hoà cùng tiếng cười. Trên cao, mặt trăng tròn vành vạnh dõi theo.',
        content: 'Trẻ con trong xóm làm gì vào đêm rằm tháng Tám?',
        options: ['Rước đèn đi khắp ngõ', 'Ngồi học bài', 'Xem phim ở nhà', 'Đi ngủ sớm'],
        correctAnswer: 0, rewardMinutes: 3,
        explanation: 'Đoạn văn viết: "trẻ con trong xóm rước đèn đi khắp ngõ".' },
    ],
  },
  {
    subject: 'Tiếng Việt', weekNumber: 25, unit: UNIT_4,
    title: 'Chính tả dấu hỏi và dấu ngã', difficulty: 3,
    questions: [
      { id: 'tv-11', subject: 'Tiếng Việt', skill: 'Chính tả',
        content: 'Từ nào dưới đây viết ĐÚNG chính tả?',
        options: ['suy nghỉ', 'suy nghĩ', 'suy nghi', 'suy nghịt'],
        correctAnswer: 1, rewardMinutes: 3,
        explanation: 'Viết đúng là "suy nghĩ" (dấu ngã). "nghỉ" (dấu hỏi) là nghỉ ngơi.' },
      { id: 'tv-w25-q1', subject: 'Tiếng Việt', skill: 'Chính tả',
        content: 'Từ nào dưới đây viết ĐÚNG chính tả?',
        options: ['nghỉ hè', 'nghĩ hè', 'nghỉ hẽ', 'nghĩ hẽ'],
        correctAnswer: 0, rewardMinutes: 3,
        explanation: '"nghỉ hè" dùng dấu hỏi vì mang nghĩa nghỉ ngơi.' },
      { id: 'tv-w25-q2', subject: 'Tiếng Việt', skill: 'Chính tả',
        content: 'Từ nào dưới đây viết ĐÚNG chính tả?',
        options: ['bảo vệ', 'bão vệ', 'bảo vẽ', 'bão vẽ'],
        correctAnswer: 0, rewardMinutes: 3,
        explanation: 'Viết đúng là "bảo vệ" — cả hai tiếng đều dấu hỏi và dấu nặng.' },
    ],
  },
  {
    subject: 'Tiếng Việt', weekNumber: 26, unit: UNIT_4,
    title: 'Mở rộng vốn từ: sáng tạo', difficulty: 3,
    questions: [
      { id: 'tv-w26-q1', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Từ nào dưới đây gần nghĩa với "sáng tạo"?',
        options: ['bắt chước', 'sáng chế', 'sao chép', 'lặp lại'],
        correctAnswer: 1, rewardMinutes: 3,
        explanation: '"sáng chế" là tạo ra cái mới, gần nghĩa với "sáng tạo".' },
      { id: 'tv-w26-q2', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Người tạo ra máy móc, thiết bị mới được gọi là gì?',
        options: ['nhà phát minh', 'khán giả', 'thủ thư', 'người mẫu'],
        correctAnswer: 0, rewardMinutes: 3,
        explanation: '"nhà phát minh" là người nghĩ ra và tạo ra cái mới.' },
      { id: 'tv-w26-q3', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Câu nào dưới đây là câu khiến?',
        options: ['Chúng ta hãy cùng sáng tạo nhé!', 'Bạn ấy rất sáng tạo.',
          'Sáng tạo là gì?', 'Ôi, ý tưởng hay quá!'],
        correctAnswer: 0, rewardMinutes: 3,
        explanation: 'Có từ "hãy" và "nhé" nên là câu khiến.' },
    ],
  },
  {
    subject: 'Tiếng Việt', weekNumber: 27, unit: UNIT_4,
    title: 'Ôn tập giữa học kì 2', difficulty: 3,
    questions: [
      { id: 'tv-w27-q1', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Câu "Những chú chim gọi nhau về tổ." dùng biện pháp gì?',
        options: ['So sánh', 'Nhân hoá', 'Không dùng biện pháp nào', 'Điệp từ'],
        correctAnswer: 1, rewardMinutes: 3,
        explanation: 'Chim biết "gọi nhau" như người nên đây là nhân hoá.' },
      { id: 'tv-w27-q2', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Câu nào dưới đây đặt dấu câu ĐÚNG?',
        options: ['Mẹ hỏi: "Con đã ăn cơm chưa?"', 'Mẹ hỏi, "Con đã ăn cơm chưa."',
          'Mẹ hỏi "Con đã ăn cơm chưa"', 'Mẹ hỏi: Con đã ăn cơm chưa?'],
        correctAnswer: 0, rewardMinutes: 3,
        explanation: 'Dấu hai chấm báo hiệu lời nói, lời nói đặt trong ngoặc kép và kết thúc bằng dấu chấm hỏi.' },
      { id: 'tv-w27-q3', subject: 'Tiếng Việt', skill: 'Chính tả',
        content: 'Từ nào dưới đây viết ĐÚNG chính tả?',
        options: ['rực rỡ', 'dực dỡ', 'giực giỡ', 'rực dỡ'],
        correctAnswer: 0, rewardMinutes: 3,
        explanation: 'Viết đúng là "rực rỡ" — cả hai tiếng đều bắt đầu bằng "r".' },
    ],
  },

  /* ====== TUẦN 28-35: TRÁI ĐẤT MÀU XANH & ÔN TẬP ====== */
  {
    subject: 'Tiếng Việt', weekNumber: 28, unit: UNIT_5,
    title: 'Từ ngữ về thiên nhiên', difficulty: 3,
    questions: [
      { id: 'tv-w28-q1', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Nhóm từ nào dưới đây đều chỉ hiện tượng thiên nhiên?',
        options: ['mưa, nắng, gió', 'bàn, ghế, tủ', 'ca sĩ, hoạ sĩ, nhạc sĩ', 'chạy, nhảy, hát'],
        correctAnswer: 0, rewardMinutes: 3,
        explanation: 'Mưa, nắng, gió đều là hiện tượng của thiên nhiên.' },
      { id: 'tv-w28-q2', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Chọn từ thích hợp: "Sau cơn mưa, bầu trời ... trở lại."',
        options: ['trong xanh', 'ồn ào', 'chật chội', 'vội vàng'],
        correctAnswer: 0, rewardMinutes: 3,
        explanation: '"trong xanh" tả bầu trời sau mưa.' },
      { id: 'tv-w28-q3', subject: 'Tiếng Việt', skill: 'Tập đọc',
        passage: 'Rừng ngập mặn ven biển như bức tường xanh che chắn cho làng. Rễ cây đan vào nhau giữ lấy đất. Nhờ có rừng, sóng lớn không tràn vào phá nhà cửa.',
        content: 'Rừng ngập mặn giúp ích gì cho làng?',
        options: ['Che chắn, ngăn sóng lớn tràn vào', 'Cho bóng mát để nghỉ ngơi',
          'Cung cấp nước uống', 'Làm nơi trồng lúa'],
        correctAnswer: 0, rewardMinutes: 3,
        explanation: 'Đoạn văn viết: "Nhờ có rừng, sóng lớn không tràn vào phá nhà cửa".' },
    ],
  },
  {
    subject: 'Tiếng Việt', weekNumber: 29, unit: UNIT_5,
    title: 'Từ ngữ về bảo vệ môi trường', difficulty: 3,
    questions: [
      { id: 'tv-w29-q1', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Việc làm nào dưới đây BẢO VỆ môi trường?',
        options: ['Vứt rác đúng nơi quy định', 'Xả rác xuống sông',
          'Chặt phá cây xanh', 'Đốt rác bừa bãi'],
        correctAnswer: 0, rewardMinutes: 3,
        explanation: 'Bỏ rác đúng nơi quy định giúp giữ môi trường sạch đẹp.' },
      { id: 'tv-w29-q2', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Từ nào TRÁI NGHĨA với "sạch sẽ"?',
        options: ['gọn gàng', 'bẩn thỉu', 'ngăn nắp', 'tinh tươm'],
        correctAnswer: 1, rewardMinutes: 3,
        explanation: '"bẩn thỉu" trái nghĩa với "sạch sẽ".' },
      { id: 'tv-w29-q3', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Đặt câu khiến kêu gọi bảo vệ môi trường, câu nào đúng nhất?',
        options: ['Chúng ta hãy trồng thêm nhiều cây xanh!', 'Cây xanh rất có ích.',
          'Bạn có thích cây xanh không?', 'Ôi, cây xanh mát quá!'],
        correctAnswer: 0, rewardMinutes: 3,
        explanation: 'Có từ "hãy" và dấu chấm than nên là câu khiến kêu gọi.' },
    ],
  },
  {
    subject: 'Tiếng Việt', weekNumber: 30, unit: UNIT_5,
    title: 'Ôn tập về so sánh và nhân hoá', difficulty: 3,
    questions: [
      { id: 'tv-w30-q1', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Câu "Mặt hồ phẳng lặng như tấm gương." dùng biện pháp gì?',
        options: ['So sánh', 'Nhân hoá', 'Cả hai', 'Không dùng biện pháp nào'],
        correctAnswer: 0, rewardMinutes: 3,
        explanation: 'Mặt hồ được so sánh với tấm gương qua từ "như".' },
      { id: 'tv-w30-q2', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Câu "Chị ong nâu chăm chỉ đi tìm mật." dùng biện pháp gì?',
        options: ['So sánh', 'Nhân hoá', 'Cả hai', 'Không dùng biện pháp nào'],
        correctAnswer: 1, rewardMinutes: 3,
        explanation: 'Ong được gọi là "chị" và có tính "chăm chỉ" như người.' },
      { id: 'tv-w30-q3', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Trong câu "Cánh diều cong cong như vầng trăng non.", vật nào được đem ra so sánh?',
        options: ['Cánh diều', 'Vầng trăng non', 'Bầu trời', 'Ngọn gió'],
        correctAnswer: 0, rewardMinutes: 3,
        explanation: '"Cánh diều" là sự vật được so sánh, "vầng trăng non" là hình ảnh dùng để so sánh.' },
    ],
  },
  {
    subject: 'Tiếng Việt', weekNumber: 31, unit: UNIT_5,
    title: 'Ôn tập về các kiểu câu', difficulty: 3,
    questions: [
      { id: 'tv-w31-q1', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Câu "Đàn cò trắng bay lượn trên cánh đồng." thuộc mẫu câu nào?',
        options: ['Ai là gì?', 'Ai làm gì?', 'Ai thế nào?', 'Ở đâu?'],
        correctAnswer: 1, rewardMinutes: 3,
        explanation: '"bay lượn" là hoạt động nên thuộc mẫu "Ai làm gì?".' },
      { id: 'tv-w31-q2', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Câu nào dưới đây là câu HỎI?',
        options: ['Trời hôm nay đẹp quá!', 'Bạn đã làm bài xong chưa?',
          'Hãy giữ gìn vệ sinh chung.', 'Em rất thích môn Tiếng Việt.'],
        correctAnswer: 1, rewardMinutes: 3,
        explanation: 'Câu có từ "chưa" và dấu chấm hỏi nên là câu hỏi.' },
      { id: 'tv-w31-q3', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Câu "Bạn Minh là lớp trưởng lớp em." thuộc mẫu câu nào?',
        options: ['Ai là gì?', 'Ai làm gì?', 'Ai thế nào?', 'Khi nào?'],
        correctAnswer: 0, rewardMinutes: 3,
        explanation: 'Có từ "là" và giới thiệu về bạn Minh.' },
    ],
  },
  {
    subject: 'Tiếng Việt', weekNumber: 32, unit: UNIT_5,
    title: 'Ôn tập về dấu câu', difficulty: 3,
    questions: [
      { id: 'tv-w32-q1', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Dấu nào dùng để kết thúc câu bộc lộ cảm xúc?',
        options: ['dấu chấm', 'dấu chấm hỏi', 'dấu chấm than', 'dấu phẩy'],
        correctAnswer: 2, rewardMinutes: 3,
        explanation: 'Câu cảm kết thúc bằng dấu chấm than.' },
      { id: 'tv-w32-q2', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Câu "Trong vườn có hoa hồng hoa cúc và hoa lan." còn thiếu dấu gì?',
        options: ['dấu phẩy', 'dấu hai chấm', 'dấu chấm hỏi', 'dấu ngoặc kép'],
        correctAnswer: 0, rewardMinutes: 3,
        explanation: 'Cần dấu phẩy ngăn cách: "hoa hồng, hoa cúc và hoa lan".' },
      { id: 'tv-w32-q3', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Dấu ngoặc kép trong câu thường dùng để làm gì?',
        options: ['Đánh dấu lời nói trực tiếp', 'Kết thúc câu kể',
          'Ngăn cách các từ cùng loại', 'Nêu lí do'],
        correctAnswer: 0, rewardMinutes: 3,
        explanation: 'Dấu ngoặc kép bao lấy lời nói trực tiếp của nhân vật.' },
    ],
  },
  {
    subject: 'Tiếng Việt', weekNumber: 33, unit: UNIT_5,
    title: 'Ôn tập chính tả tổng hợp', difficulty: 3,
    questions: [
      { id: 'tv-w33-q1', subject: 'Tiếng Việt', skill: 'Chính tả',
        content: 'Từ nào dưới đây viết ĐÚNG chính tả?',
        options: ['xuất sắc', 'suất sắc', 'xuất xắc', 'suất xắc'],
        correctAnswer: 0, rewardMinutes: 3,
        explanation: 'Viết đúng là "xuất sắc".' },
      { id: 'tv-w33-q2', subject: 'Tiếng Việt', skill: 'Chính tả',
        content: 'Từ nào dưới đây viết ĐÚNG chính tả?',
        options: ['chân trọng', 'trân trọng', 'chân chọng', 'trân chọng'],
        correctAnswer: 1, rewardMinutes: 3,
        explanation: 'Viết đúng là "trân trọng" (quý trọng).' },
      { id: 'tv-w33-q3', subject: 'Tiếng Việt', skill: 'Chính tả',
        content: 'Từ nào dưới đây viết ĐÚNG chính tả?',
        options: ['gìn giữ', 'dìn giữ', 'rìn giữ', 'gìn dữ'],
        correctAnswer: 0, rewardMinutes: 3,
        explanation: 'Viết đúng là "gìn giữ".' },
    ],
  },
  {
    subject: 'Tiếng Việt', weekNumber: 34, unit: UNIT_5,
    title: 'Ôn tập cuối năm: từ và câu', difficulty: 3,
    questions: [
      { id: 'tv-w34-q1', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Từ nào dưới đây là từ chỉ đặc điểm?',
        options: ['con sông', 'mênh mông', 'chảy xiết', 'buổi trưa'],
        correctAnswer: 1, rewardMinutes: 3,
        explanation: '"mênh mông" tả độ rộng nên là từ chỉ đặc điểm.' },
      { id: 'tv-w34-q2', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Bộ phận nào trả lời cho câu hỏi "Làm gì?" trong câu "Các bác nông dân gặt lúa ngoài đồng."',
        options: ['Các bác nông dân', 'gặt lúa', 'ngoài đồng', 'lúa'],
        correctAnswer: 1, rewardMinutes: 3,
        explanation: '"gặt lúa" là hoạt động nên trả lời cho câu hỏi "Làm gì?".' },
      { id: 'tv-w34-q3', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Cặp từ nào dưới đây CÙNG NGHĨA?',
        options: ['siêng năng — chăm chỉ', 'cao — thấp', 'sáng — tối', 'vui — buồn'],
        correctAnswer: 0, rewardMinutes: 3,
        explanation: '"siêng năng" và "chăm chỉ" cùng nghĩa; ba cặp còn lại trái nghĩa.' },
    ],
  },
  {
    subject: 'Tiếng Việt', weekNumber: 35, unit: UNIT_5,
    title: 'Ôn tập cuối năm: đọc hiểu', difficulty: 3,
    questions: [
      { id: 'tv-w35-q1', subject: 'Tiếng Việt', skill: 'Tập đọc',
        passage: 'Hè về, ve kêu râm ran trên vòm phượng đỏ. Sân trường vắng bóng học trò. Chỉ có chú chim sâu vẫn ngày ngày chuyền cành, như đang đợi tiếng trống khai trường.',
        content: 'Đoạn văn tả cảnh sân trường vào lúc nào?',
        options: ['Ngày khai giảng', 'Kì nghỉ hè', 'Giờ ra chơi', 'Buổi chào cờ'],
        correctAnswer: 1, rewardMinutes: 3,
        explanation: '"Hè về" và "Sân trường vắng bóng học trò" cho thấy đang là kì nghỉ hè.' },
      { id: 'tv-w35-q2', subject: 'Tiếng Việt', skill: 'Tập đọc',
        passage: 'Hè về, ve kêu râm ran trên vòm phượng đỏ. Sân trường vắng bóng học trò. Chỉ có chú chim sâu vẫn ngày ngày chuyền cành, như đang đợi tiếng trống khai trường.',
        content: 'Trong đoạn văn, hình ảnh nào được nhân hoá?',
        options: ['Vòm phượng đỏ', 'Chú chim sâu đợi tiếng trống', 'Tiếng ve kêu', 'Sân trường'],
        correctAnswer: 1, rewardMinutes: 3,
        explanation: 'Chim sâu biết "đợi tiếng trống khai trường" như con người.' },
      { id: 'tv-w35-q3', subject: 'Tiếng Việt', skill: 'Luyện từ và câu',
        content: 'Câu "Ve kêu râm ran trên vòm phượng đỏ." thuộc mẫu câu nào?',
        options: ['Ai là gì?', 'Ai làm gì?', 'Ai thế nào?', 'Vì sao?'],
        correctAnswer: 1, rewardMinutes: 3,
        explanation: '"kêu râm ran" là hoạt động của ve nên thuộc mẫu "Ai làm gì?".' },
    ],
  },
];

/* ------------------------------------------------------------------ */
/* Hàm truy vấn                                                        */
/* ------------------------------------------------------------------ */

export function getVietnameseWeek(weekNumber: number): WeekTopic | undefined {
  return VIETNAMESE_WEEKS.find((week) => week.weekNumber === weekNumber);
}

export function getVietnameseWeekQuestions(weekNumber: number): Question[] {
  return getVietnameseWeek(weekNumber)?.questions ?? [];
}

/** Toàn bộ câu hỏi Tiếng Việt của cả lộ trình */
export const VIETNAMESE_QUESTIONS: Question[] = VIETNAMESE_WEEKS.flatMap(
  (week) => week.questions,
);
